import type { ResourceKind } from '@/store/ui'

// The API group of every kind with a dedicated view, mirroring kindToGVR in
// internal/kube/mutate.go. CRDs reuse built-in kind names in their own groups
// (Knative's Service, Calico's NetworkPolicy, Volcano's Job), so code that maps
// a kind from external data onto a built-in view has to match the group as
// well. A Record, so a new ResourceKind can't be left out.
export const RESOURCE_KIND_GROUPS: Readonly<Record<ResourceKind, string>> = {
  Pod: '',
  Service: '',
  ConfigMap: '',
  Secret: '',
  Namespace: '',
  Node: '',
  PersistentVolumeClaim: '',
  PersistentVolume: '',
  ResourceQuota: '',
  LimitRange: '',
  Endpoints: '',
  ReplicationController: '',
  ServiceAccount: '',
  Deployment: 'apps',
  StatefulSet: 'apps',
  DaemonSet: 'apps',
  ReplicaSet: 'apps',
  Job: 'batch',
  CronJob: 'batch',
  HorizontalPodAutoscaler: 'autoscaling',
  PodDisruptionBudget: 'policy',
  Ingress: 'networking.k8s.io',
  IngressClass: 'networking.k8s.io',
  NetworkPolicy: 'networking.k8s.io',
  ServiceCIDR: 'networking.k8s.io',
  IPAddress: 'networking.k8s.io',
  EndpointSlice: 'discovery.k8s.io',
  StorageClass: 'storage.k8s.io',
  CSIDriver: 'storage.k8s.io',
  CSINode: 'storage.k8s.io',
  VolumeAttachment: 'storage.k8s.io',
  PriorityClass: 'scheduling.k8s.io',
  RuntimeClass: 'node.k8s.io',
  Lease: 'coordination.k8s.io',
  MutatingWebhookConfiguration: 'admissionregistration.k8s.io',
  ValidatingWebhookConfiguration: 'admissionregistration.k8s.io',
  ValidatingAdmissionPolicy: 'admissionregistration.k8s.io',
  ValidatingAdmissionPolicyBinding: 'admissionregistration.k8s.io',
  MutatingAdmissionPolicy: 'admissionregistration.k8s.io',
  MutatingAdmissionPolicyBinding: 'admissionregistration.k8s.io',
  DeviceClass: 'resource.k8s.io',
  ResourceSlice: 'resource.k8s.io',
  ResourceClaim: 'resource.k8s.io',
  ResourceClaimTemplate: 'resource.k8s.io',
  Role: 'rbac.authorization.k8s.io',
  RoleBinding: 'rbac.authorization.k8s.io',
  ClusterRole: 'rbac.authorization.k8s.io',
  ClusterRoleBinding: 'rbac.authorization.k8s.io',
  APIService: 'apiregistration.k8s.io',
  CertificateSigningRequest: 'certificates.k8s.io',
  FlowSchema: 'flowcontrol.apiserver.k8s.io',
  PriorityLevelConfiguration: 'flowcontrol.apiserver.k8s.io',
  Gateway: 'gateway.networking.k8s.io',
  HTTPRoute: 'gateway.networking.k8s.io',
  GRPCRoute: 'gateway.networking.k8s.io',
  TLSRoute: 'gateway.networking.k8s.io',
  TCPRoute: 'gateway.networking.k8s.io',
  UDPRoute: 'gateway.networking.k8s.io',
  ListenerSet: 'gateway.networking.k8s.io',
  BackendTLSPolicy: 'gateway.networking.k8s.io',
  GatewayClass: 'gateway.networking.k8s.io',
  ReferenceGrant: 'gateway.networking.k8s.io',
}
