import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const frontendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const bindingsPath = path.join(frontendDir, 'src/lib/wails/wailsjs/go/app/App.d.ts')
const modelsPath = path.join(frontendDir, 'src/lib/wails/wailsjs/go/models.ts')
const outputPath = path.join(frontendDir, 'src/lib/api.generated.ts')

const [bindingsSource, modelsSource] = await Promise.all([
  readFile(bindingsPath, 'utf8'),
  readFile(modelsPath, 'utf8'),
])

const bindingNames = [...bindingsSource.matchAll(/^export function (\w+)\(/gm)].map(
  ([, name]) => name,
)
if (bindingNames.length === 0) throw new Error(`No Wails bindings found in ${bindingsPath}`)

const namespaceMatches = [...modelsSource.matchAll(/^export namespace (\w+) \{/gm)]
const models = namespaceMatches.flatMap((match, index) => {
  const namespace = match[1]
  const start = match.index + match[0].length
  const end = namespaceMatches[index + 1]?.index ?? modelsSource.length
  const body = modelsSource.slice(start, end)
  return [...body.matchAll(/^\s*export class (\w+)/gm)].map(([, name]) => ({ namespace, name }))
})
if (models.length === 0) throw new Error(`No Wails models found in ${modelsPath}`)

const lowerFirst = (value) => value[0].toLowerCase() + value.slice(1)
const upperFirst = (value) => value[0].toUpperCase() + value.slice(1)
const aliasFor = ({ namespace, name }) =>
  namespace === 'kube' ? name : `${upperFirst(namespace)}${name}`

const assertUnique = (values, label) => {
  const seen = new Set()
  for (const value of values) {
    if (seen.has(value)) throw new Error(`Duplicate generated ${label}: ${value}`)
    seen.add(value)
  }
}

assertUnique(bindingNames.map(lowerFirst), 'API method')
assertUnique(models.map(aliasFor), 'model alias')

const namespaces = [...new Set(models.map(({ namespace }) => namespace))]
const output = [
  '// Generated by npm run generate:api. Do not edit.',
  "import * as bindings from '@/lib/wails/wailsjs/go/app/App'",
  `import { ${namespaces.join(', ')} } from '@/lib/wails/wailsjs/go/models'`,
  '',
  ...models.map(
    (model) => `export type ${aliasFor(model)} = ${model.namespace}.${model.name}`,
  ),
  '',
  'export const generatedApi = {',
  ...bindingNames.map((name) => `  ${lowerFirst(name)}: bindings.${name},`),
  '}',
  '',
].join('\n')

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '')
  if (current !== output) {
    console.error('Generated API facade is stale. Run npm run generate:api.')
    process.exitCode = 1
  }
} else {
  const current = await readFile(outputPath, 'utf8').catch(() => '')
  if (current !== output) await writeFile(outputPath, output)
}
