package kube

import (
	"context"
	"encoding/json"
	"reflect"
	"testing"

	"k8s.io/apimachinery/pkg/runtime/schema"
)

// A trimmed copy of the Kyverno library's disallow-latest-tag policy, the way
// the API server returns it once Kyverno has autogenerated controller rules.
const disallowLatestTag = `
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  creationTimestamp: "2026-03-02T13:12:17Z"
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: Images must be pinned to a specific tag.
spec:
  admission: true
  background: true
  validationFailureAction: Audit
  rules:
    - name: validate-image-tag
      match:
        any:
          - resources:
              kinds: [Pod]
      exclude:
        any:
          - resources:
              namespaces: [kube-system, kyverno]
      validate:
        message: Container images must have a tag specified and cannot use ':latest'.
        pattern:
          spec:
            containers:
              - image: "!*:latest & *:*"
    - name: validate-init-container-image-tag
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: Init container images must have a tag specified.
        pattern:
          spec: {}
status:
  autogen:
    rules:
      - name: autogen-validate-image-tag
        match:
          any:
            - resources:
                kinds: [StatefulSet, Deployment, DaemonSet]
  conditions:
    - type: Ready
      status: "True"
      reason: Succeeded
      message: Ready
  validatingadmissionpolicy:
    generated: false
    message: "skip generating ValidatingAdmissionPolicy: multiple rules are not applicable."
`

func TestExtractKyvernoPolicy(t *testing.T) {
	info := extractKyvernoPolicy(mustUnstructured(t, disallowLatestTag))
	want := KyvernoPolicyInfo{
		Name:       "disallow-latest-tag",
		Title:      "Disallow Latest Tag",
		Category:   "Pod Security",
		Severity:   "medium",
		Action:     "Audit",
		Background: true,
		Admission:  true,
		Ready:      "True",
		Message:    "Ready",
		Validate:   2,
		CreatedAt:  "2026-03-02T13:12:17Z",
	}
	if info != want {
		t.Fatalf("info =\n%+v\nwant\n%+v", info, want)
	}
}

func TestKyvernoFailureActionPerRuleAndDefaults(t *testing.T) {
	policy := mustUnstructured(t, `
apiVersion: kyverno.io/v1
kind: Policy
metadata: {name: p, namespace: shop}
spec:
  validationFailureAction: enforce
  rules:
    - name: inherits
      validate: {pattern: {}}
    - name: overrides
      validate: {failureAction: Audit, pattern: {}}
    - name: adds-label
      mutate: {patchStrategicMerge: {}}
`)
	info := extractKyvernoPolicy(policy)
	if info.Action != "Mixed" || info.Validate != 2 || info.Mutate != 1 {
		t.Fatalf("info = %+v", info)
	}
	// Unset admission and background default to true, as in Kyverno.
	if !info.Admission || !info.Background {
		t.Fatal("admission and background default to true")
	}
	detail := extractKyvernoPolicyDetail(policy)
	if got := []string{detail.Rules[0].FailureAction, detail.Rules[1].FailureAction, detail.Rules[2].FailureAction}; !reflect.DeepEqual(got, []string{"Enforce", "Audit", ""}) {
		t.Fatalf("failure actions = %v", got)
	}
	if detail.ReportKey != "shop/p" {
		t.Fatalf("a namespaced Policy is reported as <namespace>/<name>, got %q", detail.ReportKey)
	}
}

func TestExtractKyvernoPolicyDetail(t *testing.T) {
	detail := extractKyvernoPolicyDetail(mustUnstructured(t, disallowLatestTag))
	if detail.ReportKey != "disallow-latest-tag" || detail.Description == "" {
		t.Fatalf("detail = %+v", detail)
	}
	rule := detail.Rules[0]
	if rule.Type != "validate" || rule.Subtype != "pattern" || rule.FailureAction != "Audit" {
		t.Fatalf("rule = %+v", rule)
	}
	if rule.MatchMode != "any" || !reflect.DeepEqual(rule.Match, []string{"Pod"}) {
		t.Fatalf("match = %s %v", rule.MatchMode, rule.Match)
	}
	if !reflect.DeepEqual(rule.Exclude, []string{"namespaces: kube-system, kyverno"}) {
		t.Fatalf("exclude = %v", rule.Exclude)
	}
	if detail.Rules[1].Exclude == nil {
		t.Fatal("an absent exclude must encode as [], not null")
	}
	if want := []KyvernoAutogenRule{{Name: "autogen-validate-image-tag", Kinds: []string{"DaemonSet", "Deployment", "StatefulSet"}}}; !reflect.DeepEqual(detail.AutogenRules, want) {
		t.Fatalf("autogen = %+v", detail.AutogenRules)
	}
	if detail.VAPGenerated || detail.VAPMessage == "" {
		t.Fatalf("vap = %v %q", detail.VAPGenerated, detail.VAPMessage)
	}
}

func TestSummarizeKyvernoFilter(t *testing.T) {
	filter := mustUnstructured(t, `
any:
  - resources:
      kinds: [Pod]
      names: ["*build-images-buildkit*"]
      namespaces: [tekton-pipelines]
  - resources:
      kinds: [Deployment]
      selector:
        matchLabels: {app: web}
        matchExpressions:
          - {key: tier, operator: In, values: [front, back]}
  - subjects:
      - {kind: ServiceAccount, name: builder}
`).Object
	mode, clauses := summarizeKyvernoFilter(filter)
	want := []string{
		"Pod · namespaces: tekton-pipelines · names: *build-images-buildkit*",
		"Deployment · selector: app=web, tier In (front, back)",
		"subjects: ServiceAccount builder",
	}
	if mode != "any" || !reflect.DeepEqual(clauses, want) {
		t.Fatalf("mode = %q clauses =\n%v", mode, clauses)
	}

	// The legacy form puts one resources block directly under match.
	mode, clauses = summarizeKyvernoFilter(map[string]any{"resources": map[string]any{"kinds": []any{"Namespace"}}})
	if mode != "" || !reflect.DeepEqual(clauses, []string{"Namespace"}) {
		t.Fatalf("legacy = %q %v", mode, clauses)
	}
}

func TestGetKyvernoPolicyException(t *testing.T) {
	gvr := schema.GroupVersionResource{Group: kyvernoGroup, Version: "v2", Resource: kyvernoPolicyExceptionsResource}
	exception := mustUnstructured(t, `
apiVersion: kyverno.io/v2
kind: PolicyException
metadata: {name: buildkit-privileged, namespace: ci}
spec:
  exceptions:
    - policyName: disallow-privileged-containers
      ruleNames: [autogen-disallow-privileged-containers]
    - policyName: disallow-privileged-containers
      ruleNames: [disallow-privileged-containers]
    - policyName: restrict-seccomp
      ruleNames: [autogen-validate-seccomp-profile]
  match:
    any:
      - resources:
          kinds: [Pod]
          names: ["*buildkit*"]
`)
	m, _ := fakeCRDManager(t, []fakeCRD{{gvr: gvr, kind: "PolicyException", namespaced: true}}, exception)
	detail, err := m.GetKyvernoPolicyException(context.Background(), "ctx", "ci", "buildkit-privileged")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(detail.Policies, []string{"disallow-privileged-containers", "restrict-seccomp"}) {
		t.Fatalf("policies = %v", detail.Policies)
	}
	if len(detail.Targets) != 3 || detail.Targets[2].RuleNames[0] != "autogen-validate-seccomp-profile" {
		t.Fatalf("targets = %+v", detail.Targets)
	}
	if detail.MatchMode != "any" || !reflect.DeepEqual(detail.Match, []string{"Pod · names: *buildkit*"}) {
		t.Fatalf("match = %s %v", detail.MatchMode, detail.Match)
	}
	if !detail.Background || detail.Conditions {
		t.Fatalf("background = %v conditions = %v", detail.Background, detail.Conditions)
	}
}

const requireCostCenter = `
apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: require-cost-center
  namespace: demo-storefront
  creationTimestamp: "2026-10-04T10:47:11Z"
spec:
  validationActions: [Audit]
  evaluation:
    background: {enabled: false}
  matchConstraints:
    objectSelector:
      matchLabels: {app.kubernetes.io/part-of: demo-storefront}
    resourceRules:
      - apiGroups: [apps]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [deployments]
      - apiGroups: [""]
        apiVersions: [v1]
        operations: [CREATE]
        resources: [pods]
  matchConditions:
    - name: not-a-dry-run
      expression: "!request.dryRun"
  validations:
    - expression: "has(object.metadata.labels) && 'cost-center' in object.metadata.labels"
      message: The label cost-center is required for chargeback.
status:
  conditionStatus:
    ready: true
    conditions:
      - type: WebhookConfigured
        status: "True"
        reason: Succeeded
        message: Webhook configured.
`

func TestExtractKyvernoValidatingPolicy(t *testing.T) {
	obj := mustUnstructured(t, requireCostCenter)
	info := extractKyvernoValidatingPolicy(obj)
	if !reflect.DeepEqual(info.Actions, []string{"Audit"}) || info.Validations != 1 || info.Ready != "True" {
		t.Fatalf("info = %+v", info)
	}
	if !reflect.DeepEqual(info.Resources, []string{"deployments.apps (CREATE, UPDATE)", "pods (CREATE)"}) {
		t.Fatalf("resources = %v", info.Resources)
	}
	if !info.Admission || info.Background {
		t.Fatalf("admission defaults to true, background was disabled: %+v", info)
	}

	detail := extractKyvernoValidatingPolicyDetail(obj)
	if detail.ReportKey != "demo-storefront/require-cost-center" {
		t.Fatalf("report key = %q", detail.ReportKey)
	}
	if detail.ObjectSelector != "app.kubernetes.io/part-of=demo-storefront" || detail.NamespaceSelector != "" {
		t.Fatalf("selectors = %q / %q", detail.ObjectSelector, detail.NamespaceSelector)
	}
	if len(detail.MatchConditions) != 1 || detail.MatchConditions[0].Name != "not-a-dry-run" {
		t.Fatalf("match conditions = %+v", detail.MatchConditions)
	}
	if len(detail.Validations) != 1 || detail.Validations[0].Message == "" || len(detail.Conditions) != 1 {
		t.Fatalf("detail = %+v", detail)
	}
	b, _ := json.Marshal(detail)
	var decoded map[string]any
	_ = json.Unmarshal(b, &decoded)
	for _, field := range []string{"variables", "auditAnnotations", "validationRules", "conditions"} {
		if decoded[field] == nil {
			t.Fatalf("%s encodes as null", field)
		}
	}
}
