// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';
import {update} from '../models';

export function AddHelmRepo(arg1:string,arg2:string):Promise<void>;

export function ApplyResourceYAML(arg1:string,arg2:string):Promise<void>;

export function ApproveCertificateSigningRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CertManagerCertificateRequestsFor(arg1:string,arg2:string,arg3:string):Promise<Array<kube.CertManagerCertificateRequestInfo>>;

export function CertManagerChallengesFor(arg1:string,arg2:string,arg3:string):Promise<Array<kube.CertManagerChallengeInfo>>;

export function CertManagerOrdersFor(arg1:string,arg2:string,arg3:string):Promise<Array<kube.CertManagerOrderInfo>>;

export function CheckForUpdate():Promise<update.Result>;

export function CordonNode(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteArgoApplication(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DenyCertificateSigningRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DrainNode(arg1:string,arg2:string):Promise<void>;

export function DryRunApplyResourceYAML(arg1:string,arg2:string):Promise<kube.MutationDiff>;

export function EnsureCustomResourceWatch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function FetchMetricsServerManifest():Promise<string>;

export function GetAPIService(arg1:string,arg2:string):Promise<kube.APIServiceDetail>;

export function GetArgoAppProject(arg1:string,arg2:string,arg3:string):Promise<kube.ArgoAppProjectDetail>;

export function GetArgoApplicationOperationState(arg1:string,arg2:string,arg3:string):Promise<kube.ArgoOperationState>;

export function GetArgoApplicationSet(arg1:string,arg2:string,arg3:string):Promise<kube.ArgoApplicationSetDetail>;

export function GetCSIDriver(arg1:string,arg2:string):Promise<kube.CSIDriverDetail>;

export function GetCSINode(arg1:string,arg2:string):Promise<kube.CSINodeDetail>;

export function GetCertManagerCertificate(arg1:string,arg2:string,arg3:string):Promise<kube.CertManagerCertificateDetail>;

export function GetCertManagerCertificateRequest(arg1:string,arg2:string,arg3:string):Promise<kube.CertManagerCertificateRequestDetail>;

export function GetCertManagerChallenge(arg1:string,arg2:string,arg3:string):Promise<kube.CertManagerChallengeDetail>;

export function GetCertManagerClusterIssuer(arg1:string,arg2:string):Promise<kube.CertManagerIssuerDetail>;

export function GetCertManagerIssuer(arg1:string,arg2:string,arg3:string):Promise<kube.CertManagerIssuerDetail>;

export function GetCertManagerOrder(arg1:string,arg2:string,arg3:string):Promise<kube.CertManagerOrderDetail>;

export function GetCertificateSigningRequest(arg1:string,arg2:string):Promise<kube.CertificateSigningRequestDetail>;

export function GetClusterOverview(arg1:string):Promise<kube.ClusterOverview>;

export function GetClusterRole(arg1:string,arg2:string):Promise<kube.ClusterRoleDetail>;

export function GetClusterRoleBinding(arg1:string,arg2:string):Promise<kube.ClusterRoleBindingDetail>;

export function GetConfigMap(arg1:string,arg2:string,arg3:string):Promise<kube.ConfigMapDetail>;

export function GetCronJob(arg1:string,arg2:string,arg3:string):Promise<kube.CronJobDetail>;

export function GetCustomResourceYAML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function GetDaemonSet(arg1:string,arg2:string,arg3:string):Promise<kube.DaemonSetDetail>;

export function GetDeployment(arg1:string,arg2:string,arg3:string):Promise<kube.DeploymentDetail>;

export function GetDeviceClass(arg1:string,arg2:string):Promise<kube.DeviceClassDetail>;

export function GetEndpointSlice(arg1:string,arg2:string,arg3:string):Promise<kube.EndpointSliceDetail>;

export function GetEndpoints(arg1:string,arg2:string,arg3:string):Promise<kube.EndpointsDetail>;

export function GetFlowSchema(arg1:string,arg2:string):Promise<kube.FlowSchemaDetail>;

export function GetFluxAlert(arg1:string,arg2:string,arg3:string):Promise<kube.FluxAlertDetail>;

export function GetFluxBucket(arg1:string,arg2:string,arg3:string):Promise<kube.FluxBucketDetail>;

export function GetFluxGitRepository(arg1:string,arg2:string,arg3:string):Promise<kube.FluxGitRepositoryDetail>;

export function GetFluxHelmRelease(arg1:string,arg2:string,arg3:string):Promise<kube.FluxHelmReleaseDetail>;

export function GetFluxHelmRepository(arg1:string,arg2:string,arg3:string):Promise<kube.FluxHelmRepositoryDetail>;

export function GetFluxKustomization(arg1:string,arg2:string,arg3:string):Promise<kube.FluxKustomizationDetail>;

export function GetFluxOCIRepository(arg1:string,arg2:string,arg3:string):Promise<kube.FluxOCIRepositoryDetail>;

export function GetFluxProvider(arg1:string,arg2:string,arg3:string):Promise<kube.FluxProviderDetail>;

export function GetFluxReceiver(arg1:string,arg2:string,arg3:string):Promise<kube.FluxReceiverDetail>;

export function GetGRPCRoute(arg1:string,arg2:string,arg3:string):Promise<kube.GRPCRouteDetail>;

export function GetGateway(arg1:string,arg2:string,arg3:string):Promise<kube.GatewayDetail>;

export function GetGatewayClass(arg1:string,arg2:string):Promise<kube.GatewayClassDetail>;

export function GetHTTPRoute(arg1:string,arg2:string,arg3:string):Promise<kube.HTTPRouteDetail>;

export function GetHelmRelease(arg1:string,arg2:string,arg3:string):Promise<kube.HelmReleaseDetail>;

export function GetHorizontalPodAutoscaler(arg1:string,arg2:string,arg3:string):Promise<kube.HorizontalPodAutoscalerDetail>;

export function GetIPAddress(arg1:string,arg2:string):Promise<kube.IPAddressDetail>;

export function GetIngress(arg1:string,arg2:string,arg3:string):Promise<kube.IngressDetail>;

export function GetIngressClass(arg1:string,arg2:string):Promise<kube.IngressClassDetail>;

export function GetIstioDestinationRule(arg1:string,arg2:string,arg3:string):Promise<kube.IstioDestinationRuleDetail>;

export function GetIstioPeerAuthentication(arg1:string,arg2:string,arg3:string):Promise<kube.IstioPeerAuthenticationDetail>;

export function GetIstioVirtualService(arg1:string,arg2:string,arg3:string):Promise<kube.IstioVirtualServiceDetail>;

export function GetJob(arg1:string,arg2:string,arg3:string):Promise<kube.JobDetail>;

export function GetLease(arg1:string,arg2:string,arg3:string):Promise<kube.LeaseDetail>;

export function GetLimitRange(arg1:string,arg2:string,arg3:string):Promise<kube.LimitRangeDetail>;

export function GetMutatingAdmissionPolicy(arg1:string,arg2:string):Promise<kube.AdmissionPolicyDetail>;

export function GetMutatingAdmissionPolicyBinding(arg1:string,arg2:string):Promise<kube.AdmissionPolicyBindingDetail>;

export function GetMutatingWebhookConfiguration(arg1:string,arg2:string):Promise<kube.WebhookConfigurationDetail>;

export function GetNamespace(arg1:string,arg2:string):Promise<kube.NamespaceDetail>;

export function GetNetworkPolicy(arg1:string,arg2:string,arg3:string):Promise<kube.NetworkPolicyDetail>;

export function GetNode(arg1:string,arg2:string):Promise<kube.NodeDetail>;

export function GetPersistentVolume(arg1:string,arg2:string):Promise<kube.PersistentVolumeDetail>;

export function GetPersistentVolumeClaim(arg1:string,arg2:string,arg3:string):Promise<kube.PersistentVolumeClaimDetail>;

export function GetPod(arg1:string,arg2:string,arg3:string):Promise<kube.PodDetail>;

export function GetPodDisruptionBudget(arg1:string,arg2:string,arg3:string):Promise<kube.PodDisruptionBudgetDetail>;

export function GetPriorityClass(arg1:string,arg2:string):Promise<kube.PriorityClassDetail>;

export function GetPriorityLevelConfiguration(arg1:string,arg2:string):Promise<kube.PriorityLevelConfigurationDetail>;

export function GetReferenceGrant(arg1:string,arg2:string,arg3:string):Promise<kube.ReferenceGrantDetail>;

export function GetReplicaSet(arg1:string,arg2:string,arg3:string):Promise<kube.ReplicaSetDetail>;

export function GetReplicationController(arg1:string,arg2:string,arg3:string):Promise<kube.ReplicationControllerDetail>;

export function GetResourceClaim(arg1:string,arg2:string,arg3:string):Promise<kube.ResourceClaimDetail>;

export function GetResourceClaimTemplate(arg1:string,arg2:string,arg3:string):Promise<kube.ResourceClaimTemplateDetail>;

export function GetResourceQuota(arg1:string,arg2:string,arg3:string):Promise<kube.ResourceQuotaDetail>;

export function GetResourceSlice(arg1:string,arg2:string):Promise<kube.ResourceSliceDetail>;

export function GetResourceYAML(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetRole(arg1:string,arg2:string,arg3:string):Promise<kube.RoleDetail>;

export function GetRoleBinding(arg1:string,arg2:string,arg3:string):Promise<kube.RoleBindingDetail>;

export function GetRuntimeClass(arg1:string,arg2:string):Promise<kube.RuntimeClassDetail>;

export function GetSecret(arg1:string,arg2:string,arg3:string):Promise<kube.SecretDetail>;

export function GetService(arg1:string,arg2:string,arg3:string):Promise<kube.ServiceDetail>;

export function GetServiceAccount(arg1:string,arg2:string,arg3:string):Promise<kube.ServiceAccountDetail>;

export function GetServiceCIDR(arg1:string,arg2:string):Promise<kube.ServiceCIDRDetail>;

export function GetStatefulSet(arg1:string,arg2:string,arg3:string):Promise<kube.StatefulSetDetail>;

export function GetStorageClass(arg1:string,arg2:string):Promise<kube.StorageClassDetail>;

export function GetSubjectAccess(arg1:string,arg2:string,arg3:string,arg4:string):Promise<kube.SubjectAccess>;

export function GetValidatingAdmissionPolicy(arg1:string,arg2:string):Promise<kube.AdmissionPolicyDetail>;

export function GetValidatingAdmissionPolicyBinding(arg1:string,arg2:string):Promise<kube.AdmissionPolicyBindingDetail>;

export function GetValidatingWebhookConfiguration(arg1:string,arg2:string):Promise<kube.WebhookConfigurationDetail>;

export function GetVolumeAttachment(arg1:string,arg2:string):Promise<kube.VolumeAttachmentDetail>;

export function GetWorkloadRevisionTemplate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function HelmChartVersions(arg1:string,arg2:string):Promise<Array<string>>;

export function InstallHelmRelease(arg1:kube.HelmInstallOptions):Promise<kube.HelmDryRunResult>;

export function IsMetricsServerKlustrManaged(arg1:string):Promise<boolean>;

export function ListAPIServices(arg1:string):Promise<Array<kube.APIServiceInfo>>;

export function ListAccessSubjects(arg1:string):Promise<Array<kube.AccessSubject>>;

export function ListAccessibleKinds(arg1:string):Promise<Array<string>>;

export function ListArgoAppProjects(arg1:string,arg2:string):Promise<Array<kube.ArgoAppProjectInfo>>;

export function ListArgoApplicationHistory(arg1:string,arg2:string,arg3:string):Promise<Array<kube.ArgoApplicationHistoryEntry>>;

export function ListArgoApplicationResources(arg1:string,arg2:string,arg3:string):Promise<Array<kube.ArgoApplicationResource>>;

export function ListArgoApplicationSets(arg1:string,arg2:string):Promise<Array<kube.ArgoApplicationSetInfo>>;

export function ListArgoApplications(arg1:string,arg2:string):Promise<Array<kube.ArgoApplicationInfo>>;

export function ListCRDs(arg1:string):Promise<Array<kube.CRDInfo>>;

export function ListCSIDrivers(arg1:string):Promise<Array<kube.CSIDriverInfo>>;

export function ListCSINodes(arg1:string):Promise<Array<kube.CSINodeInfo>>;

export function ListCertManagerCertificateRequests(arg1:string,arg2:string):Promise<Array<kube.CertManagerCertificateRequestInfo>>;

export function ListCertManagerCertificates(arg1:string,arg2:string):Promise<Array<kube.CertManagerCertificateInfo>>;

export function ListCertManagerChallenges(arg1:string,arg2:string):Promise<Array<kube.CertManagerChallengeInfo>>;

export function ListCertManagerClusterIssuers(arg1:string):Promise<Array<kube.CertManagerIssuerInfo>>;

export function ListCertManagerIssuers(arg1:string,arg2:string):Promise<Array<kube.CertManagerIssuerInfo>>;

export function ListCertManagerOrders(arg1:string,arg2:string):Promise<Array<kube.CertManagerOrderInfo>>;

export function ListCertificateSigningRequests(arg1:string):Promise<Array<kube.CertificateSigningRequestInfo>>;

export function ListClusterRoleBindings(arg1:string):Promise<Array<kube.ClusterRoleBindingInfo>>;

export function ListClusterRoles(arg1:string):Promise<Array<kube.ClusterRoleInfo>>;

export function ListClusterWarningEvents(arg1:string,arg2:number):Promise<Array<kube.EventInfo>>;

export function ListConfigMaps(arg1:string,arg2:string):Promise<Array<kube.ConfigMapInfo>>;

export function ListContexts():Promise<kube.Kubeconfig>;

export function ListCronJobs(arg1:string,arg2:string):Promise<Array<kube.CronJobInfo>>;

export function ListCustomResources(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<kube.CustomResourceInfo>>;

export function ListDaemonSetRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<kube.WorkloadRevision>>;

export function ListDaemonSets(arg1:string,arg2:string):Promise<Array<kube.DaemonSetInfo>>;

export function ListDeploymentRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<kube.WorkloadRevision>>;

export function ListDeployments(arg1:string,arg2:string):Promise<Array<kube.DeploymentInfo>>;

export function ListDeviceClasses(arg1:string):Promise<Array<kube.DeviceClassInfo>>;

export function ListEndpointSlices(arg1:string,arg2:string):Promise<Array<kube.EndpointSliceInfo>>;

export function ListEndpoints(arg1:string,arg2:string):Promise<Array<kube.EndpointsInfo>>;

export function ListEvents(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<kube.EventInfo>>;

export function ListFlowSchemas(arg1:string):Promise<Array<kube.FlowSchemaInfo>>;

export function ListFluxAlerts(arg1:string,arg2:string):Promise<Array<kube.FluxAlertInfo>>;

export function ListFluxBuckets(arg1:string,arg2:string):Promise<Array<kube.FluxBucketInfo>>;

export function ListFluxGitRepositories(arg1:string,arg2:string):Promise<Array<kube.FluxGitRepositoryInfo>>;

export function ListFluxHelmReleases(arg1:string,arg2:string):Promise<Array<kube.FluxHelmReleaseInfo>>;

export function ListFluxHelmRepositories(arg1:string,arg2:string):Promise<Array<kube.FluxHelmRepositoryInfo>>;

export function ListFluxKustomizations(arg1:string,arg2:string):Promise<Array<kube.FluxKustomizationInfo>>;

export function ListFluxOCIRepositories(arg1:string,arg2:string):Promise<Array<kube.FluxOCIRepositoryInfo>>;

export function ListFluxProviders(arg1:string,arg2:string):Promise<Array<kube.FluxProviderInfo>>;

export function ListFluxReceivers(arg1:string,arg2:string):Promise<Array<kube.FluxReceiverInfo>>;

export function ListGRPCRoutes(arg1:string,arg2:string):Promise<Array<kube.GRPCRouteInfo>>;

export function ListGatewayClasses(arg1:string):Promise<Array<kube.GatewayClassInfo>>;

export function ListGateways(arg1:string,arg2:string):Promise<Array<kube.GatewayInfo>>;

export function ListHTTPRoutes(arg1:string,arg2:string):Promise<Array<kube.HTTPRouteInfo>>;

export function ListHelmReleaseHistory(arg1:string,arg2:string,arg3:string):Promise<Array<kube.HelmRevisionInfo>>;

export function ListHelmReleases(arg1:string,arg2:string):Promise<Array<kube.HelmReleaseInfo>>;

export function ListHelmRepos():Promise<Array<kube.HelmRepoInfo>>;

export function ListHorizontalPodAutoscalers(arg1:string,arg2:string):Promise<Array<kube.HorizontalPodAutoscalerInfo>>;

export function ListIPAddresses(arg1:string):Promise<Array<kube.IPAddressInfo>>;

export function ListIngressClasses(arg1:string):Promise<Array<kube.IngressClassInfo>>;

export function ListIngresses(arg1:string,arg2:string):Promise<Array<kube.IngressInfo>>;

export function ListIstioDestinationRules(arg1:string,arg2:string):Promise<Array<kube.IstioDestinationRuleInfo>>;

export function ListIstioPeerAuthentications(arg1:string,arg2:string):Promise<Array<kube.IstioPeerAuthenticationInfo>>;

export function ListIstioVirtualServices(arg1:string,arg2:string):Promise<Array<kube.IstioVirtualServiceInfo>>;

export function ListJobs(arg1:string,arg2:string):Promise<Array<kube.JobInfo>>;

export function ListKarpenterNodeClaims(arg1:string):Promise<Array<kube.KarpenterNodeClaimInfo>>;

export function ListKarpenterNodePools(arg1:string):Promise<Array<kube.KarpenterNodePoolInfo>>;

export function ListLeases(arg1:string,arg2:string):Promise<Array<kube.LeaseInfo>>;

export function ListLimitRanges(arg1:string,arg2:string):Promise<Array<kube.LimitRangeInfo>>;

export function ListMutatingAdmissionPolicies(arg1:string):Promise<Array<kube.AdmissionPolicyInfo>>;

export function ListMutatingAdmissionPolicyBindings(arg1:string):Promise<Array<kube.AdmissionPolicyBindingInfo>>;

export function ListMutatingWebhookConfigurations(arg1:string):Promise<Array<kube.WebhookConfigurationInfo>>;

export function ListNamespaces(arg1:string):Promise<Array<kube.NamespaceInfo>>;

export function ListNetworkPolicies(arg1:string,arg2:string):Promise<Array<kube.NetworkPolicyInfo>>;

export function ListNodeClaimNode(arg1:string,arg2:string):Promise<Array<kube.NodeInfo>>;

export function ListNodeMetrics(arg1:string):Promise<Array<kube.NodeMetrics>>;

export function ListNodePoolNodes(arg1:string,arg2:string):Promise<Array<kube.NodeInfo>>;

export function ListNodes(arg1:string):Promise<Array<kube.NodeInfo>>;

export function ListPersistentVolumeClaims(arg1:string,arg2:string):Promise<Array<kube.PersistentVolumeClaimInfo>>;

export function ListPersistentVolumes(arg1:string):Promise<Array<kube.PersistentVolumeInfo>>;

export function ListPodDisruptionBudgets(arg1:string,arg2:string):Promise<Array<kube.PodDisruptionBudgetInfo>>;

export function ListPodMetrics(arg1:string,arg2:string):Promise<Array<kube.PodMetrics>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<kube.PodInfo>>;

export function ListPortForwards():Promise<Array<kube.PortForwardInfo>>;

export function ListPriorityClasses(arg1:string):Promise<Array<kube.PriorityClassInfo>>;

export function ListPriorityLevelConfigurations(arg1:string):Promise<Array<kube.PriorityLevelConfigurationInfo>>;

export function ListReferenceGrants(arg1:string,arg2:string):Promise<Array<kube.ReferenceGrantInfo>>;

export function ListReplicaSets(arg1:string,arg2:string):Promise<Array<kube.ReplicaSetInfo>>;

export function ListReplicationControllers(arg1:string,arg2:string):Promise<Array<kube.ReplicationControllerInfo>>;

export function ListResourceClaimTemplates(arg1:string,arg2:string):Promise<Array<kube.ResourceClaimTemplateInfo>>;

export function ListResourceClaims(arg1:string,arg2:string):Promise<Array<kube.ResourceClaimInfo>>;

export function ListResourceQuotas(arg1:string,arg2:string):Promise<Array<kube.ResourceQuotaInfo>>;

export function ListResourceSlices(arg1:string):Promise<Array<kube.ResourceSliceInfo>>;

export function ListRoleBindings(arg1:string,arg2:string):Promise<Array<kube.RoleBindingInfo>>;

export function ListRoles(arg1:string,arg2:string):Promise<Array<kube.RoleInfo>>;

export function ListRuntimeClasses(arg1:string):Promise<Array<kube.RuntimeClassInfo>>;

export function ListSecrets(arg1:string,arg2:string):Promise<Array<kube.SecretInfo>>;

export function ListServiceAccounts(arg1:string,arg2:string):Promise<Array<kube.ServiceAccountInfo>>;

export function ListServiceCIDRs(arg1:string):Promise<Array<kube.ServiceCIDRInfo>>;

export function ListServices(arg1:string,arg2:string):Promise<Array<kube.ServiceInfo>>;

export function ListStatefulSetRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<kube.WorkloadRevision>>;

export function ListStatefulSets(arg1:string,arg2:string):Promise<Array<kube.StatefulSetInfo>>;

export function ListStorageClasses(arg1:string):Promise<Array<kube.StorageClassInfo>>;

export function ListSystemTerminals():Promise<Array<kube.SystemTerminal>>;

export function ListValidatingAdmissionPolicies(arg1:string):Promise<Array<kube.AdmissionPolicyInfo>>;

export function ListValidatingAdmissionPolicyBindings(arg1:string):Promise<Array<kube.AdmissionPolicyBindingInfo>>;

export function ListValidatingWebhookConfigurations(arg1:string):Promise<Array<kube.WebhookConfigurationInfo>>;

export function ListVolumeAttachments(arg1:string):Promise<Array<kube.VolumeAttachmentInfo>>;

export function OpenInSystemTerminal(arg1:string,arg2:string):Promise<void>;

export function OpenLocalTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function OpenPodExecInSystemTerminal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function PatchDeploymentPaused(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function PatchHPAReplicas(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function PingContext(arg1:string):Promise<kube.ServerVersion>;

export function PodLogTargets(arg1:string,arg2:string,arg3:Record<string, string>):Promise<Array<kube.PodLogTarget>>;

export function PodsForOwner(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<kube.PodInfo>>;

export function RecommendInsecureKubeletTLS(arg1:string):Promise<boolean>;

export function ReconcileFluxResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RefreshArgoApplication(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RemoveHelmRepo(arg1:string):Promise<void>;

export function RenewCertificate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeExec(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeLocalTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizePodResources(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function RestartWorkload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RevealSecretValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RollbackArgoApplication(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function RollbackDaemonSet(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function RollbackDeployment(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function RollbackHelmRelease(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function RollbackStatefulSet(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function ScaleResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function SearchHelmCharts(arg1:string):Promise<Array<kube.HelmChartSearchResult>>;

export function SendExecInput(arg1:string,arg2:string):Promise<void>;

export function SendLocalTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetArgoApplicationAutomation(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetFluxResourceSuspended(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetReadOnly(arg1:string,arg2:boolean):Promise<void>;

export function StartExec(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<string>;

export function StartNodeShell(arg1:string,arg2:string):Promise<string>;

export function StartPodLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:number):Promise<string>;

export function StartPortForward(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<kube.PortForwardInfo>;

export function StartWatch(arg1:string):Promise<void>;

export function StopExec(arg1:string):Promise<void>;

export function StopLocalTerminal(arg1:string):Promise<void>;

export function StopPodLogs(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function StopWatch(arg1:string):Promise<void>;

export function SyncArgoApplication(arg1:string,arg2:string,arg3:string,arg4:kube.ArgoSyncOptions):Promise<void>;

export function UninstallHelmRelease(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UpdateHelmRepos():Promise<void>;

export function UpgradeHelmRelease(arg1:kube.HelmInstallOptions):Promise<kube.HelmDryRunResult>;

export function Version():Promise<string>;
