// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHelmRepo(arg1, arg2) {
  return window['go']['app']['App']['AddHelmRepo'](arg1, arg2);
}

export function ApplyResourceYAML(arg1, arg2) {
  return window['go']['app']['App']['ApplyResourceYAML'](arg1, arg2);
}

export function ApproveCertificateSigningRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApproveCertificateSigningRequest'](arg1, arg2, arg3);
}

export function CertManagerCertificateRequestsFor(arg1, arg2, arg3) {
  return window['go']['app']['App']['CertManagerCertificateRequestsFor'](arg1, arg2, arg3);
}

export function CertManagerChallengesFor(arg1, arg2, arg3) {
  return window['go']['app']['App']['CertManagerChallengesFor'](arg1, arg2, arg3);
}

export function CertManagerOrdersFor(arg1, arg2, arg3) {
  return window['go']['app']['App']['CertManagerOrdersFor'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function CordonNode(arg1, arg2, arg3) {
  return window['go']['app']['App']['CordonNode'](arg1, arg2, arg3);
}

export function DeleteArgoApplication(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteArgoApplication'](arg1, arg2, arg3, arg4);
}

export function DeleteResource(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteResource'](arg1, arg2, arg3, arg4);
}

export function DenyCertificateSigningRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['DenyCertificateSigningRequest'](arg1, arg2, arg3);
}

export function DrainNode(arg1, arg2) {
  return window['go']['app']['App']['DrainNode'](arg1, arg2);
}

export function DryRunApplyResourceYAML(arg1, arg2) {
  return window['go']['app']['App']['DryRunApplyResourceYAML'](arg1, arg2);
}

export function EnsureCustomResourceWatch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['EnsureCustomResourceWatch'](arg1, arg2, arg3, arg4);
}

export function FetchMetricsServerManifest() {
  return window['go']['app']['App']['FetchMetricsServerManifest']();
}

export function GetAPIService(arg1, arg2) {
  return window['go']['app']['App']['GetAPIService'](arg1, arg2);
}

export function GetArgoAppProject(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetArgoAppProject'](arg1, arg2, arg3);
}

export function GetArgoApplicationOperationState(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetArgoApplicationOperationState'](arg1, arg2, arg3);
}

export function GetArgoApplicationSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetArgoApplicationSet'](arg1, arg2, arg3);
}

export function GetCSIDriver(arg1, arg2) {
  return window['go']['app']['App']['GetCSIDriver'](arg1, arg2);
}

export function GetCSINode(arg1, arg2) {
  return window['go']['app']['App']['GetCSINode'](arg1, arg2);
}

export function GetCertManagerCertificate(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCertManagerCertificate'](arg1, arg2, arg3);
}

export function GetCertManagerCertificateRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCertManagerCertificateRequest'](arg1, arg2, arg3);
}

export function GetCertManagerChallenge(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCertManagerChallenge'](arg1, arg2, arg3);
}

export function GetCertManagerClusterIssuer(arg1, arg2) {
  return window['go']['app']['App']['GetCertManagerClusterIssuer'](arg1, arg2);
}

export function GetCertManagerIssuer(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCertManagerIssuer'](arg1, arg2, arg3);
}

export function GetCertManagerOrder(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCertManagerOrder'](arg1, arg2, arg3);
}

export function GetCertificateSigningRequest(arg1, arg2) {
  return window['go']['app']['App']['GetCertificateSigningRequest'](arg1, arg2);
}

export function GetClusterOverview(arg1) {
  return window['go']['app']['App']['GetClusterOverview'](arg1);
}

export function GetClusterRole(arg1, arg2) {
  return window['go']['app']['App']['GetClusterRole'](arg1, arg2);
}

export function GetClusterRoleBinding(arg1, arg2) {
  return window['go']['app']['App']['GetClusterRoleBinding'](arg1, arg2);
}

export function GetConfigMap(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConfigMap'](arg1, arg2, arg3);
}

export function GetCronJob(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCronJob'](arg1, arg2, arg3);
}

export function GetCustomResourceYAML(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetCustomResourceYAML'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDaemonSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDaemonSet'](arg1, arg2, arg3);
}

export function GetDeployment(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDeployment'](arg1, arg2, arg3);
}

export function GetDeviceClass(arg1, arg2) {
  return window['go']['app']['App']['GetDeviceClass'](arg1, arg2);
}

export function GetEndpointSlice(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetEndpointSlice'](arg1, arg2, arg3);
}

export function GetEndpoints(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetEndpoints'](arg1, arg2, arg3);
}

export function GetFlowSchema(arg1, arg2) {
  return window['go']['app']['App']['GetFlowSchema'](arg1, arg2);
}

export function GetFluxAlert(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxAlert'](arg1, arg2, arg3);
}

export function GetFluxBucket(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxBucket'](arg1, arg2, arg3);
}

export function GetFluxGitRepository(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxGitRepository'](arg1, arg2, arg3);
}

export function GetFluxHelmRelease(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxHelmRelease'](arg1, arg2, arg3);
}

export function GetFluxHelmRepository(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxHelmRepository'](arg1, arg2, arg3);
}

export function GetFluxKustomization(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxKustomization'](arg1, arg2, arg3);
}

export function GetFluxOCIRepository(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxOCIRepository'](arg1, arg2, arg3);
}

export function GetFluxProvider(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxProvider'](arg1, arg2, arg3);
}

export function GetFluxReceiver(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFluxReceiver'](arg1, arg2, arg3);
}

export function GetGRPCRoute(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetGRPCRoute'](arg1, arg2, arg3);
}

export function GetGateway(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetGateway'](arg1, arg2, arg3);
}

export function GetGatewayClass(arg1, arg2) {
  return window['go']['app']['App']['GetGatewayClass'](arg1, arg2);
}

export function GetHTTPRoute(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHTTPRoute'](arg1, arg2, arg3);
}

export function GetHelmRelease(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHelmRelease'](arg1, arg2, arg3);
}

export function GetHorizontalPodAutoscaler(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHorizontalPodAutoscaler'](arg1, arg2, arg3);
}

export function GetIPAddress(arg1, arg2) {
  return window['go']['app']['App']['GetIPAddress'](arg1, arg2);
}

export function GetIngress(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIngress'](arg1, arg2, arg3);
}

export function GetIngressClass(arg1, arg2) {
  return window['go']['app']['App']['GetIngressClass'](arg1, arg2);
}

export function GetIstioDestinationRule(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIstioDestinationRule'](arg1, arg2, arg3);
}

export function GetIstioPeerAuthentication(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIstioPeerAuthentication'](arg1, arg2, arg3);
}

export function GetIstioVirtualService(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIstioVirtualService'](arg1, arg2, arg3);
}

export function GetJob(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetJob'](arg1, arg2, arg3);
}

export function GetLease(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetLease'](arg1, arg2, arg3);
}

export function GetLimitRange(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetLimitRange'](arg1, arg2, arg3);
}

export function GetMutatingAdmissionPolicy(arg1, arg2) {
  return window['go']['app']['App']['GetMutatingAdmissionPolicy'](arg1, arg2);
}

export function GetMutatingAdmissionPolicyBinding(arg1, arg2) {
  return window['go']['app']['App']['GetMutatingAdmissionPolicyBinding'](arg1, arg2);
}

export function GetMutatingWebhookConfiguration(arg1, arg2) {
  return window['go']['app']['App']['GetMutatingWebhookConfiguration'](arg1, arg2);
}

export function GetNamespace(arg1, arg2) {
  return window['go']['app']['App']['GetNamespace'](arg1, arg2);
}

export function GetNetworkPolicy(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetNetworkPolicy'](arg1, arg2, arg3);
}

export function GetNode(arg1, arg2) {
  return window['go']['app']['App']['GetNode'](arg1, arg2);
}

export function GetPersistentVolume(arg1, arg2) {
  return window['go']['app']['App']['GetPersistentVolume'](arg1, arg2);
}

export function GetPersistentVolumeClaim(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPersistentVolumeClaim'](arg1, arg2, arg3);
}

export function GetPod(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPod'](arg1, arg2, arg3);
}

export function GetPodDisruptionBudget(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPodDisruptionBudget'](arg1, arg2, arg3);
}

export function GetPriorityClass(arg1, arg2) {
  return window['go']['app']['App']['GetPriorityClass'](arg1, arg2);
}

export function GetPriorityLevelConfiguration(arg1, arg2) {
  return window['go']['app']['App']['GetPriorityLevelConfiguration'](arg1, arg2);
}

export function GetReferenceGrant(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetReferenceGrant'](arg1, arg2, arg3);
}

export function GetReplicaSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetReplicaSet'](arg1, arg2, arg3);
}

export function GetReplicationController(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetReplicationController'](arg1, arg2, arg3);
}

export function GetResourceClaim(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetResourceClaim'](arg1, arg2, arg3);
}

export function GetResourceClaimTemplate(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetResourceClaimTemplate'](arg1, arg2, arg3);
}

export function GetResourceQuota(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetResourceQuota'](arg1, arg2, arg3);
}

export function GetResourceSlice(arg1, arg2) {
  return window['go']['app']['App']['GetResourceSlice'](arg1, arg2);
}

export function GetResourceYAML(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetResourceYAML'](arg1, arg2, arg3, arg4);
}

export function GetRole(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetRole'](arg1, arg2, arg3);
}

export function GetRoleBinding(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetRoleBinding'](arg1, arg2, arg3);
}

export function GetRuntimeClass(arg1, arg2) {
  return window['go']['app']['App']['GetRuntimeClass'](arg1, arg2);
}

export function GetSecret(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSecret'](arg1, arg2, arg3);
}

export function GetService(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetService'](arg1, arg2, arg3);
}

export function GetServiceAccount(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetServiceAccount'](arg1, arg2, arg3);
}

export function GetServiceCIDR(arg1, arg2) {
  return window['go']['app']['App']['GetServiceCIDR'](arg1, arg2);
}

export function GetStatefulSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStatefulSet'](arg1, arg2, arg3);
}

export function GetStorageClass(arg1, arg2) {
  return window['go']['app']['App']['GetStorageClass'](arg1, arg2);
}

export function GetSubjectAccess(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetSubjectAccess'](arg1, arg2, arg3, arg4);
}

export function GetValidatingAdmissionPolicy(arg1, arg2) {
  return window['go']['app']['App']['GetValidatingAdmissionPolicy'](arg1, arg2);
}

export function GetValidatingAdmissionPolicyBinding(arg1, arg2) {
  return window['go']['app']['App']['GetValidatingAdmissionPolicyBinding'](arg1, arg2);
}

export function GetValidatingWebhookConfiguration(arg1, arg2) {
  return window['go']['app']['App']['GetValidatingWebhookConfiguration'](arg1, arg2);
}

export function GetVolumeAttachment(arg1, arg2) {
  return window['go']['app']['App']['GetVolumeAttachment'](arg1, arg2);
}

export function GetWorkloadRevisionTemplate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetWorkloadRevisionTemplate'](arg1, arg2, arg3, arg4, arg5);
}

export function HelmChartVersions(arg1, arg2) {
  return window['go']['app']['App']['HelmChartVersions'](arg1, arg2);
}

export function InstallHelmRelease(arg1) {
  return window['go']['app']['App']['InstallHelmRelease'](arg1);
}

export function IsMetricsServerKlustrManaged(arg1) {
  return window['go']['app']['App']['IsMetricsServerKlustrManaged'](arg1);
}

export function ListAPIServices(arg1) {
  return window['go']['app']['App']['ListAPIServices'](arg1);
}

export function ListAccessSubjects(arg1) {
  return window['go']['app']['App']['ListAccessSubjects'](arg1);
}

export function ListAccessibleKinds(arg1) {
  return window['go']['app']['App']['ListAccessibleKinds'](arg1);
}

export function ListArgoAppProjects(arg1, arg2) {
  return window['go']['app']['App']['ListArgoAppProjects'](arg1, arg2);
}

export function ListArgoApplicationHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListArgoApplicationHistory'](arg1, arg2, arg3);
}

export function ListArgoApplicationResources(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListArgoApplicationResources'](arg1, arg2, arg3);
}

export function ListArgoApplicationSets(arg1, arg2) {
  return window['go']['app']['App']['ListArgoApplicationSets'](arg1, arg2);
}

export function ListArgoApplications(arg1, arg2) {
  return window['go']['app']['App']['ListArgoApplications'](arg1, arg2);
}

export function ListCRDs(arg1) {
  return window['go']['app']['App']['ListCRDs'](arg1);
}

export function ListCSIDrivers(arg1) {
  return window['go']['app']['App']['ListCSIDrivers'](arg1);
}

export function ListCSINodes(arg1) {
  return window['go']['app']['App']['ListCSINodes'](arg1);
}

export function ListCertManagerCertificateRequests(arg1, arg2) {
  return window['go']['app']['App']['ListCertManagerCertificateRequests'](arg1, arg2);
}

export function ListCertManagerCertificates(arg1, arg2) {
  return window['go']['app']['App']['ListCertManagerCertificates'](arg1, arg2);
}

export function ListCertManagerChallenges(arg1, arg2) {
  return window['go']['app']['App']['ListCertManagerChallenges'](arg1, arg2);
}

export function ListCertManagerClusterIssuers(arg1) {
  return window['go']['app']['App']['ListCertManagerClusterIssuers'](arg1);
}

export function ListCertManagerIssuers(arg1, arg2) {
  return window['go']['app']['App']['ListCertManagerIssuers'](arg1, arg2);
}

export function ListCertManagerOrders(arg1, arg2) {
  return window['go']['app']['App']['ListCertManagerOrders'](arg1, arg2);
}

export function ListCertificateSigningRequests(arg1) {
  return window['go']['app']['App']['ListCertificateSigningRequests'](arg1);
}

export function ListClusterRoleBindings(arg1) {
  return window['go']['app']['App']['ListClusterRoleBindings'](arg1);
}

export function ListClusterRoles(arg1) {
  return window['go']['app']['App']['ListClusterRoles'](arg1);
}

export function ListClusterWarningEvents(arg1, arg2) {
  return window['go']['app']['App']['ListClusterWarningEvents'](arg1, arg2);
}

export function ListConfigMaps(arg1, arg2) {
  return window['go']['app']['App']['ListConfigMaps'](arg1, arg2);
}

export function ListContexts() {
  return window['go']['app']['App']['ListContexts']();
}

export function ListCronJobs(arg1, arg2) {
  return window['go']['app']['App']['ListCronJobs'](arg1, arg2);
}

export function ListCustomResources(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListCustomResources'](arg1, arg2, arg3, arg4, arg5);
}

export function ListDaemonSetRevisions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDaemonSetRevisions'](arg1, arg2, arg3);
}

export function ListDaemonSets(arg1, arg2) {
  return window['go']['app']['App']['ListDaemonSets'](arg1, arg2);
}

export function ListDeploymentRevisions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDeploymentRevisions'](arg1, arg2, arg3);
}

export function ListDeployments(arg1, arg2) {
  return window['go']['app']['App']['ListDeployments'](arg1, arg2);
}

export function ListDeviceClasses(arg1) {
  return window['go']['app']['App']['ListDeviceClasses'](arg1);
}

export function ListEndpointSlices(arg1, arg2) {
  return window['go']['app']['App']['ListEndpointSlices'](arg1, arg2);
}

export function ListEndpoints(arg1, arg2) {
  return window['go']['app']['App']['ListEndpoints'](arg1, arg2);
}

export function ListEvents(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListEvents'](arg1, arg2, arg3, arg4);
}

export function ListFlowSchemas(arg1) {
  return window['go']['app']['App']['ListFlowSchemas'](arg1);
}

export function ListFluxAlerts(arg1, arg2) {
  return window['go']['app']['App']['ListFluxAlerts'](arg1, arg2);
}

export function ListFluxBuckets(arg1, arg2) {
  return window['go']['app']['App']['ListFluxBuckets'](arg1, arg2);
}

export function ListFluxGitRepositories(arg1, arg2) {
  return window['go']['app']['App']['ListFluxGitRepositories'](arg1, arg2);
}

export function ListFluxHelmReleases(arg1, arg2) {
  return window['go']['app']['App']['ListFluxHelmReleases'](arg1, arg2);
}

export function ListFluxHelmRepositories(arg1, arg2) {
  return window['go']['app']['App']['ListFluxHelmRepositories'](arg1, arg2);
}

export function ListFluxKustomizations(arg1, arg2) {
  return window['go']['app']['App']['ListFluxKustomizations'](arg1, arg2);
}

export function ListFluxOCIRepositories(arg1, arg2) {
  return window['go']['app']['App']['ListFluxOCIRepositories'](arg1, arg2);
}

export function ListFluxProviders(arg1, arg2) {
  return window['go']['app']['App']['ListFluxProviders'](arg1, arg2);
}

export function ListFluxReceivers(arg1, arg2) {
  return window['go']['app']['App']['ListFluxReceivers'](arg1, arg2);
}

export function ListGRPCRoutes(arg1, arg2) {
  return window['go']['app']['App']['ListGRPCRoutes'](arg1, arg2);
}

export function ListGatewayClasses(arg1) {
  return window['go']['app']['App']['ListGatewayClasses'](arg1);
}

export function ListGateways(arg1, arg2) {
  return window['go']['app']['App']['ListGateways'](arg1, arg2);
}

export function ListHTTPRoutes(arg1, arg2) {
  return window['go']['app']['App']['ListHTTPRoutes'](arg1, arg2);
}

export function ListHelmReleaseHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListHelmReleaseHistory'](arg1, arg2, arg3);
}

export function ListHelmReleases(arg1, arg2) {
  return window['go']['app']['App']['ListHelmReleases'](arg1, arg2);
}

export function ListHelmRepos() {
  return window['go']['app']['App']['ListHelmRepos']();
}

export function ListHorizontalPodAutoscalers(arg1, arg2) {
  return window['go']['app']['App']['ListHorizontalPodAutoscalers'](arg1, arg2);
}

export function ListIPAddresses(arg1) {
  return window['go']['app']['App']['ListIPAddresses'](arg1);
}

export function ListIngressClasses(arg1) {
  return window['go']['app']['App']['ListIngressClasses'](arg1);
}

export function ListIngresses(arg1, arg2) {
  return window['go']['app']['App']['ListIngresses'](arg1, arg2);
}

export function ListIstioDestinationRules(arg1, arg2) {
  return window['go']['app']['App']['ListIstioDestinationRules'](arg1, arg2);
}

export function ListIstioPeerAuthentications(arg1, arg2) {
  return window['go']['app']['App']['ListIstioPeerAuthentications'](arg1, arg2);
}

export function ListIstioVirtualServices(arg1, arg2) {
  return window['go']['app']['App']['ListIstioVirtualServices'](arg1, arg2);
}

export function ListJobs(arg1, arg2) {
  return window['go']['app']['App']['ListJobs'](arg1, arg2);
}

export function ListKarpenterNodeClaims(arg1) {
  return window['go']['app']['App']['ListKarpenterNodeClaims'](arg1);
}

export function ListKarpenterNodePools(arg1) {
  return window['go']['app']['App']['ListKarpenterNodePools'](arg1);
}

export function ListLeases(arg1, arg2) {
  return window['go']['app']['App']['ListLeases'](arg1, arg2);
}

export function ListLimitRanges(arg1, arg2) {
  return window['go']['app']['App']['ListLimitRanges'](arg1, arg2);
}

export function ListMutatingAdmissionPolicies(arg1) {
  return window['go']['app']['App']['ListMutatingAdmissionPolicies'](arg1);
}

export function ListMutatingAdmissionPolicyBindings(arg1) {
  return window['go']['app']['App']['ListMutatingAdmissionPolicyBindings'](arg1);
}

export function ListMutatingWebhookConfigurations(arg1) {
  return window['go']['app']['App']['ListMutatingWebhookConfigurations'](arg1);
}

export function ListNamespaces(arg1) {
  return window['go']['app']['App']['ListNamespaces'](arg1);
}

export function ListNetworkPolicies(arg1, arg2) {
  return window['go']['app']['App']['ListNetworkPolicies'](arg1, arg2);
}

export function ListNodeClaimNode(arg1, arg2) {
  return window['go']['app']['App']['ListNodeClaimNode'](arg1, arg2);
}

export function ListNodeMetrics(arg1) {
  return window['go']['app']['App']['ListNodeMetrics'](arg1);
}

export function ListNodePoolNodes(arg1, arg2) {
  return window['go']['app']['App']['ListNodePoolNodes'](arg1, arg2);
}

export function ListNodes(arg1) {
  return window['go']['app']['App']['ListNodes'](arg1);
}

export function ListPersistentVolumeClaims(arg1, arg2) {
  return window['go']['app']['App']['ListPersistentVolumeClaims'](arg1, arg2);
}

export function ListPersistentVolumes(arg1) {
  return window['go']['app']['App']['ListPersistentVolumes'](arg1);
}

export function ListPodDisruptionBudgets(arg1, arg2) {
  return window['go']['app']['App']['ListPodDisruptionBudgets'](arg1, arg2);
}

export function ListPodMetrics(arg1, arg2) {
  return window['go']['app']['App']['ListPodMetrics'](arg1, arg2);
}

export function ListPods(arg1, arg2) {
  return window['go']['app']['App']['ListPods'](arg1, arg2);
}

export function ListPortForwards() {
  return window['go']['app']['App']['ListPortForwards']();
}

export function ListPriorityClasses(arg1) {
  return window['go']['app']['App']['ListPriorityClasses'](arg1);
}

export function ListPriorityLevelConfigurations(arg1) {
  return window['go']['app']['App']['ListPriorityLevelConfigurations'](arg1);
}

export function ListReferenceGrants(arg1, arg2) {
  return window['go']['app']['App']['ListReferenceGrants'](arg1, arg2);
}

export function ListReplicaSets(arg1, arg2) {
  return window['go']['app']['App']['ListReplicaSets'](arg1, arg2);
}

export function ListReplicationControllers(arg1, arg2) {
  return window['go']['app']['App']['ListReplicationControllers'](arg1, arg2);
}

export function ListResourceClaimTemplates(arg1, arg2) {
  return window['go']['app']['App']['ListResourceClaimTemplates'](arg1, arg2);
}

export function ListResourceClaims(arg1, arg2) {
  return window['go']['app']['App']['ListResourceClaims'](arg1, arg2);
}

export function ListResourceQuotas(arg1, arg2) {
  return window['go']['app']['App']['ListResourceQuotas'](arg1, arg2);
}

export function ListResourceSlices(arg1) {
  return window['go']['app']['App']['ListResourceSlices'](arg1);
}

export function ListRoleBindings(arg1, arg2) {
  return window['go']['app']['App']['ListRoleBindings'](arg1, arg2);
}

export function ListRoles(arg1, arg2) {
  return window['go']['app']['App']['ListRoles'](arg1, arg2);
}

export function ListRuntimeClasses(arg1) {
  return window['go']['app']['App']['ListRuntimeClasses'](arg1);
}

export function ListSecrets(arg1, arg2) {
  return window['go']['app']['App']['ListSecrets'](arg1, arg2);
}

export function ListServiceAccounts(arg1, arg2) {
  return window['go']['app']['App']['ListServiceAccounts'](arg1, arg2);
}

export function ListServiceCIDRs(arg1) {
  return window['go']['app']['App']['ListServiceCIDRs'](arg1);
}

export function ListServices(arg1, arg2) {
  return window['go']['app']['App']['ListServices'](arg1, arg2);
}

export function ListStatefulSetRevisions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListStatefulSetRevisions'](arg1, arg2, arg3);
}

export function ListStatefulSets(arg1, arg2) {
  return window['go']['app']['App']['ListStatefulSets'](arg1, arg2);
}

export function ListStorageClasses(arg1) {
  return window['go']['app']['App']['ListStorageClasses'](arg1);
}

export function ListSystemTerminals() {
  return window['go']['app']['App']['ListSystemTerminals']();
}

export function ListValidatingAdmissionPolicies(arg1) {
  return window['go']['app']['App']['ListValidatingAdmissionPolicies'](arg1);
}

export function ListValidatingAdmissionPolicyBindings(arg1) {
  return window['go']['app']['App']['ListValidatingAdmissionPolicyBindings'](arg1);
}

export function ListValidatingWebhookConfigurations(arg1) {
  return window['go']['app']['App']['ListValidatingWebhookConfigurations'](arg1);
}

export function ListVolumeAttachments(arg1) {
  return window['go']['app']['App']['ListVolumeAttachments'](arg1);
}

export function OpenInSystemTerminal(arg1, arg2) {
  return window['go']['app']['App']['OpenInSystemTerminal'](arg1, arg2);
}

export function OpenLocalTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenLocalTerminal'](arg1, arg2, arg3);
}

export function OpenPodExecInSystemTerminal(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['OpenPodExecInSystemTerminal'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PatchDeploymentPaused(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PatchDeploymentPaused'](arg1, arg2, arg3, arg4);
}

export function PatchHPAReplicas(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['PatchHPAReplicas'](arg1, arg2, arg3, arg4, arg5);
}

export function PingContext(arg1) {
  return window['go']['app']['App']['PingContext'](arg1);
}

export function PodLogTargets(arg1, arg2, arg3) {
  return window['go']['app']['App']['PodLogTargets'](arg1, arg2, arg3);
}

export function PodsForOwner(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PodsForOwner'](arg1, arg2, arg3, arg4);
}

export function RecommendInsecureKubeletTLS(arg1) {
  return window['go']['app']['App']['RecommendInsecureKubeletTLS'](arg1);
}

export function ReconcileFluxResource(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ReconcileFluxResource'](arg1, arg2, arg3, arg4);
}

export function RefreshArgoApplication(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RefreshArgoApplication'](arg1, arg2, arg3, arg4);
}

export function RemoveHelmRepo(arg1) {
  return window['go']['app']['App']['RemoveHelmRepo'](arg1);
}

export function RenewCertificate(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenewCertificate'](arg1, arg2, arg3);
}

export function ResizeExec(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeExec'](arg1, arg2, arg3);
}

export function ResizeLocalTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeLocalTerminal'](arg1, arg2, arg3);
}

export function RestartWorkload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RestartWorkload'](arg1, arg2, arg3, arg4);
}

export function RevealSecretValue(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RevealSecretValue'](arg1, arg2, arg3, arg4);
}

export function RollbackArgoApplication(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RollbackArgoApplication'](arg1, arg2, arg3, arg4, arg5);
}

export function RollbackDaemonSet(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RollbackDaemonSet'](arg1, arg2, arg3, arg4);
}

export function RollbackDeployment(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RollbackDeployment'](arg1, arg2, arg3, arg4);
}

export function RollbackHelmRelease(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RollbackHelmRelease'](arg1, arg2, arg3, arg4, arg5);
}

export function RollbackStatefulSet(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RollbackStatefulSet'](arg1, arg2, arg3, arg4);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['app']['App']['SaveTextFile'](arg1, arg2);
}

export function ScaleResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ScaleResource'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchHelmCharts(arg1) {
  return window['go']['app']['App']['SearchHelmCharts'](arg1);
}

export function SendExecInput(arg1, arg2) {
  return window['go']['app']['App']['SendExecInput'](arg1, arg2);
}

export function SendLocalTerminalInput(arg1, arg2) {
  return window['go']['app']['App']['SendLocalTerminalInput'](arg1, arg2);
}

export function SetArgoApplicationAutomation(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetArgoApplicationAutomation'](arg1, arg2, arg3, arg4);
}

export function SetFluxResourceSuspended(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SetFluxResourceSuspended'](arg1, arg2, arg3, arg4, arg5);
}

export function SetReadOnly(arg1, arg2) {
  return window['go']['app']['App']['SetReadOnly'](arg1, arg2);
}

export function StartExec(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartExec'](arg1, arg2, arg3, arg4, arg5);
}

export function StartNodeShell(arg1, arg2) {
  return window['go']['app']['App']['StartNodeShell'](arg1, arg2);
}

export function StartPodLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StartPodLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartPortForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StartWatch(arg1) {
  return window['go']['app']['App']['StartWatch'](arg1);
}

export function StopExec(arg1) {
  return window['go']['app']['App']['StopExec'](arg1);
}

export function StopLocalTerminal(arg1) {
  return window['go']['app']['App']['StopLocalTerminal'](arg1);
}

export function StopPodLogs(arg1) {
  return window['go']['app']['App']['StopPodLogs'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['app']['App']['StopPortForward'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['app']['App']['StopWatch'](arg1);
}

export function SyncArgoApplication(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SyncArgoApplication'](arg1, arg2, arg3, arg4);
}

export function UninstallHelmRelease(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UninstallHelmRelease'](arg1, arg2, arg3, arg4);
}

export function UpdateHelmRepos() {
  return window['go']['app']['App']['UpdateHelmRepos']();
}

export function UpgradeHelmRelease(arg1) {
  return window['go']['app']['App']['UpgradeHelmRelease'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
