// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHelmRepo(arg1, arg2) {
  return window['go']['app']['App']['AddHelmRepo'](arg1, arg2);
}

export function ApplyResourceYAML(arg1, arg2) {
  return window['go']['app']['App']['ApplyResourceYAML'](arg1, arg2);
}

export function DeleteResource(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteResource'](arg1, arg2, arg3, arg4);
}

export function EnsureCustomResourceWatch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['EnsureCustomResourceWatch'](arg1, arg2, arg3, arg4);
}

export function GetClusterOverview(arg1) {
  return window['go']['app']['App']['GetClusterOverview'](arg1);
}

export function GetConfigMap(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConfigMap'](arg1, arg2, arg3);
}

export function GetCronJob(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCronJob'](arg1, arg2, arg3);
}

export function GetCustomResourceYAML(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetCustomResourceYAML'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDaemonSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDaemonSet'](arg1, arg2, arg3);
}

export function GetDeployment(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDeployment'](arg1, arg2, arg3);
}

export function GetEndpointSlice(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetEndpointSlice'](arg1, arg2, arg3);
}

export function GetEndpoints(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetEndpoints'](arg1, arg2, arg3);
}

export function GetHelmRelease(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHelmRelease'](arg1, arg2, arg3);
}

export function GetHorizontalPodAutoscaler(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHorizontalPodAutoscaler'](arg1, arg2, arg3);
}

export function GetIngress(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIngress'](arg1, arg2, arg3);
}

export function GetIngressClass(arg1, arg2) {
  return window['go']['app']['App']['GetIngressClass'](arg1, arg2);
}

export function GetJob(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetJob'](arg1, arg2, arg3);
}

export function GetLease(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetLease'](arg1, arg2, arg3);
}

export function GetLimitRange(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetLimitRange'](arg1, arg2, arg3);
}

export function GetMutatingWebhookConfiguration(arg1, arg2) {
  return window['go']['app']['App']['GetMutatingWebhookConfiguration'](arg1, arg2);
}

export function GetNamespace(arg1, arg2) {
  return window['go']['app']['App']['GetNamespace'](arg1, arg2);
}

export function GetNetworkPolicy(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetNetworkPolicy'](arg1, arg2, arg3);
}

export function GetNode(arg1, arg2) {
  return window['go']['app']['App']['GetNode'](arg1, arg2);
}

export function GetPersistentVolume(arg1, arg2) {
  return window['go']['app']['App']['GetPersistentVolume'](arg1, arg2);
}

export function GetPersistentVolumeClaim(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPersistentVolumeClaim'](arg1, arg2, arg3);
}

export function GetPod(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPod'](arg1, arg2, arg3);
}

export function GetPodDisruptionBudget(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPodDisruptionBudget'](arg1, arg2, arg3);
}

export function GetPriorityClass(arg1, arg2) {
  return window['go']['app']['App']['GetPriorityClass'](arg1, arg2);
}

export function GetReplicaSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetReplicaSet'](arg1, arg2, arg3);
}

export function GetReplicationController(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetReplicationController'](arg1, arg2, arg3);
}

export function GetResourceQuota(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetResourceQuota'](arg1, arg2, arg3);
}

export function GetResourceYAML(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetResourceYAML'](arg1, arg2, arg3, arg4);
}

export function GetRuntimeClass(arg1, arg2) {
  return window['go']['app']['App']['GetRuntimeClass'](arg1, arg2);
}

export function GetSecret(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSecret'](arg1, arg2, arg3);
}

export function GetService(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetService'](arg1, arg2, arg3);
}

export function GetStatefulSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStatefulSet'](arg1, arg2, arg3);
}

export function GetStorageClass(arg1, arg2) {
  return window['go']['app']['App']['GetStorageClass'](arg1, arg2);
}

export function GetValidatingWebhookConfiguration(arg1, arg2) {
  return window['go']['app']['App']['GetValidatingWebhookConfiguration'](arg1, arg2);
}

export function HelmChartVersions(arg1, arg2) {
  return window['go']['app']['App']['HelmChartVersions'](arg1, arg2);
}

export function InstallHelmRelease(arg1) {
  return window['go']['app']['App']['InstallHelmRelease'](arg1);
}

export function ListArgoApplicationResources(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListArgoApplicationResources'](arg1, arg2, arg3);
}

export function ListArgoApplications(arg1, arg2) {
  return window['go']['app']['App']['ListArgoApplications'](arg1, arg2);
}

export function ListCRDs(arg1) {
  return window['go']['app']['App']['ListCRDs'](arg1);
}

export function ListClusterWarningEvents(arg1, arg2) {
  return window['go']['app']['App']['ListClusterWarningEvents'](arg1, arg2);
}

export function ListConfigMaps(arg1, arg2) {
  return window['go']['app']['App']['ListConfigMaps'](arg1, arg2);
}

export function ListContexts() {
  return window['go']['app']['App']['ListContexts']();
}

export function ListCronJobs(arg1, arg2) {
  return window['go']['app']['App']['ListCronJobs'](arg1, arg2);
}

export function ListCustomResources(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListCustomResources'](arg1, arg2, arg3, arg4, arg5);
}

export function ListDaemonSets(arg1, arg2) {
  return window['go']['app']['App']['ListDaemonSets'](arg1, arg2);
}

export function ListDeployments(arg1, arg2) {
  return window['go']['app']['App']['ListDeployments'](arg1, arg2);
}

export function ListEndpointSlices(arg1, arg2) {
  return window['go']['app']['App']['ListEndpointSlices'](arg1, arg2);
}

export function ListEndpoints(arg1, arg2) {
  return window['go']['app']['App']['ListEndpoints'](arg1, arg2);
}

export function ListEvents(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListEvents'](arg1, arg2, arg3, arg4);
}

export function ListHelmReleaseHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListHelmReleaseHistory'](arg1, arg2, arg3);
}

export function ListHelmReleases(arg1, arg2) {
  return window['go']['app']['App']['ListHelmReleases'](arg1, arg2);
}

export function ListHelmRepos() {
  return window['go']['app']['App']['ListHelmRepos']();
}

export function ListHorizontalPodAutoscalers(arg1, arg2) {
  return window['go']['app']['App']['ListHorizontalPodAutoscalers'](arg1, arg2);
}

export function ListIngressClasses(arg1) {
  return window['go']['app']['App']['ListIngressClasses'](arg1);
}

export function ListIngresses(arg1, arg2) {
  return window['go']['app']['App']['ListIngresses'](arg1, arg2);
}

export function ListJobs(arg1, arg2) {
  return window['go']['app']['App']['ListJobs'](arg1, arg2);
}

export function ListLeases(arg1, arg2) {
  return window['go']['app']['App']['ListLeases'](arg1, arg2);
}

export function ListLimitRanges(arg1, arg2) {
  return window['go']['app']['App']['ListLimitRanges'](arg1, arg2);
}

export function ListMutatingWebhookConfigurations(arg1) {
  return window['go']['app']['App']['ListMutatingWebhookConfigurations'](arg1);
}

export function ListNamespaces(arg1) {
  return window['go']['app']['App']['ListNamespaces'](arg1);
}

export function ListNetworkPolicies(arg1, arg2) {
  return window['go']['app']['App']['ListNetworkPolicies'](arg1, arg2);
}

export function ListNodes(arg1) {
  return window['go']['app']['App']['ListNodes'](arg1);
}

export function ListPersistentVolumeClaims(arg1, arg2) {
  return window['go']['app']['App']['ListPersistentVolumeClaims'](arg1, arg2);
}

export function ListPersistentVolumes(arg1) {
  return window['go']['app']['App']['ListPersistentVolumes'](arg1);
}

export function ListPodDisruptionBudgets(arg1, arg2) {
  return window['go']['app']['App']['ListPodDisruptionBudgets'](arg1, arg2);
}

export function ListPodMetrics(arg1, arg2) {
  return window['go']['app']['App']['ListPodMetrics'](arg1, arg2);
}

export function ListPods(arg1, arg2) {
  return window['go']['app']['App']['ListPods'](arg1, arg2);
}

export function ListPortForwards() {
  return window['go']['app']['App']['ListPortForwards']();
}

export function ListPriorityClasses(arg1) {
  return window['go']['app']['App']['ListPriorityClasses'](arg1);
}

export function ListReplicaSets(arg1, arg2) {
  return window['go']['app']['App']['ListReplicaSets'](arg1, arg2);
}

export function ListReplicationControllers(arg1, arg2) {
  return window['go']['app']['App']['ListReplicationControllers'](arg1, arg2);
}

export function ListResourceQuotas(arg1, arg2) {
  return window['go']['app']['App']['ListResourceQuotas'](arg1, arg2);
}

export function ListRuntimeClasses(arg1) {
  return window['go']['app']['App']['ListRuntimeClasses'](arg1);
}

export function ListSecrets(arg1, arg2) {
  return window['go']['app']['App']['ListSecrets'](arg1, arg2);
}

export function ListServices(arg1, arg2) {
  return window['go']['app']['App']['ListServices'](arg1, arg2);
}

export function ListStatefulSets(arg1, arg2) {
  return window['go']['app']['App']['ListStatefulSets'](arg1, arg2);
}

export function ListStorageClasses(arg1) {
  return window['go']['app']['App']['ListStorageClasses'](arg1);
}

export function ListValidatingWebhookConfigurations(arg1) {
  return window['go']['app']['App']['ListValidatingWebhookConfigurations'](arg1);
}

export function PingContext(arg1) {
  return window['go']['app']['App']['PingContext'](arg1);
}

export function PodLogTargets(arg1, arg2, arg3) {
  return window['go']['app']['App']['PodLogTargets'](arg1, arg2, arg3);
}

export function PodsForOwner(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PodsForOwner'](arg1, arg2, arg3, arg4);
}

export function RefreshArgoApplication(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RefreshArgoApplication'](arg1, arg2, arg3, arg4);
}

export function RemoveHelmRepo(arg1) {
  return window['go']['app']['App']['RemoveHelmRepo'](arg1);
}

export function ResizeExec(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeExec'](arg1, arg2, arg3);
}

export function RestartWorkload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RestartWorkload'](arg1, arg2, arg3, arg4);
}

export function RevealSecretValue(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RevealSecretValue'](arg1, arg2, arg3, arg4);
}

export function RollbackHelmRelease(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RollbackHelmRelease'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['app']['App']['SaveTextFile'](arg1, arg2);
}

export function ScaleResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ScaleResource'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchHelmCharts(arg1) {
  return window['go']['app']['App']['SearchHelmCharts'](arg1);
}

export function SendExecInput(arg1, arg2) {
  return window['go']['app']['App']['SendExecInput'](arg1, arg2);
}

export function StartExec(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartExec'](arg1, arg2, arg3, arg4, arg5);
}

export function StartPodLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StartPodLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartPortForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StartWatch(arg1) {
  return window['go']['app']['App']['StartWatch'](arg1);
}

export function StopExec(arg1) {
  return window['go']['app']['App']['StopExec'](arg1);
}

export function StopPodLogs(arg1) {
  return window['go']['app']['App']['StopPodLogs'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['app']['App']['StopPortForward'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['app']['App']['StopWatch'](arg1);
}

export function SyncArgoApplication(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SyncArgoApplication'](arg1, arg2, arg3, arg4, arg5);
}

export function UninstallHelmRelease(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UninstallHelmRelease'](arg1, arg2, arg3, arg4);
}

export function UpdateHelmRepos() {
  return window['go']['app']['App']['UpdateHelmRepos']();
}

export function UpgradeHelmRelease(arg1) {
  return window['go']['app']['App']['UpgradeHelmRelease'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
