// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';

export function AddHelmRepo(arg1:string,arg2:string):Promise<void>;

export function ApplyResourceYAML(arg1:string,arg2:string):Promise<void>;

export function ApproveCertificateSigningRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DenyCertificateSigningRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EnsureCustomResourceWatch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function FetchMetricsServerManifest():Promise<string>;

export function GetAPIService(arg1:string,arg2:string):Promise<kube.APIServiceDetail>;

export function GetCSIDriver(arg1:string,arg2:string):Promise<kube.CSIDriverDetail>;

export function GetCSINode(arg1:string,arg2:string):Promise<kube.CSINodeDetail>;

export function GetCertificateSigningRequest(arg1:string,arg2:string):Promise<kube.CertificateSigningRequestDetail>;

export function GetClusterOverview(arg1:string):Promise<kube.ClusterOverview>;

export function GetClusterRole(arg1:string,arg2:string):Promise<kube.ClusterRoleDetail>;

export function GetClusterRoleBinding(arg1:string,arg2:string):Promise<kube.ClusterRoleBindingDetail>;

export function GetConfigMap(arg1:string,arg2:string,arg3:string):Promise<kube.ConfigMapDetail>;

export function GetCronJob(arg1:string,arg2:string,arg3:string):Promise<kube.CronJobDetail>;

export function GetCustomResourceYAML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function GetDaemonSet(arg1:string,arg2:string,arg3:string):Promise<kube.DaemonSetDetail>;

export function GetDeployment(arg1:string,arg2:string,arg3:string):Promise<kube.DeploymentDetail>;

export function GetEndpointSlice(arg1:string,arg2:string,arg3:string):Promise<kube.EndpointSliceDetail>;

export function GetEndpoints(arg1:string,arg2:string,arg3:string):Promise<kube.EndpointsDetail>;

export function GetGRPCRoute(arg1:string,arg2:string,arg3:string):Promise<kube.GRPCRouteDetail>;

export function GetGateway(arg1:string,arg2:string,arg3:string):Promise<kube.GatewayDetail>;

export function GetGatewayClass(arg1:string,arg2:string):Promise<kube.GatewayClassDetail>;

export function GetHTTPRoute(arg1:string,arg2:string,arg3:string):Promise<kube.HTTPRouteDetail>;

export function GetHelmRelease(arg1:string,arg2:string,arg3:string):Promise<kube.HelmReleaseDetail>;

export function GetHorizontalPodAutoscaler(arg1:string,arg2:string,arg3:string):Promise<kube.HorizontalPodAutoscalerDetail>;

export function GetIngress(arg1:string,arg2:string,arg3:string):Promise<kube.IngressDetail>;

export function GetIngressClass(arg1:string,arg2:string):Promise<kube.IngressClassDetail>;

export function GetJob(arg1:string,arg2:string,arg3:string):Promise<kube.JobDetail>;

export function GetLease(arg1:string,arg2:string,arg3:string):Promise<kube.LeaseDetail>;

export function GetLimitRange(arg1:string,arg2:string,arg3:string):Promise<kube.LimitRangeDetail>;

export function GetMutatingWebhookConfiguration(arg1:string,arg2:string):Promise<kube.WebhookConfigurationDetail>;

export function GetNamespace(arg1:string,arg2:string):Promise<kube.NamespaceDetail>;

export function GetNetworkPolicy(arg1:string,arg2:string,arg3:string):Promise<kube.NetworkPolicyDetail>;

export function GetNode(arg1:string,arg2:string):Promise<kube.NodeDetail>;

export function GetPersistentVolume(arg1:string,arg2:string):Promise<kube.PersistentVolumeDetail>;

export function GetPersistentVolumeClaim(arg1:string,arg2:string,arg3:string):Promise<kube.PersistentVolumeClaimDetail>;

export function GetPod(arg1:string,arg2:string,arg3:string):Promise<kube.PodDetail>;

export function GetPodDisruptionBudget(arg1:string,arg2:string,arg3:string):Promise<kube.PodDisruptionBudgetDetail>;

export function GetPriorityClass(arg1:string,arg2:string):Promise<kube.PriorityClassDetail>;

export function GetReferenceGrant(arg1:string,arg2:string,arg3:string):Promise<kube.ReferenceGrantDetail>;

export function GetReplicaSet(arg1:string,arg2:string,arg3:string):Promise<kube.ReplicaSetDetail>;

export function GetReplicationController(arg1:string,arg2:string,arg3:string):Promise<kube.ReplicationControllerDetail>;

export function GetResourceQuota(arg1:string,arg2:string,arg3:string):Promise<kube.ResourceQuotaDetail>;

export function GetResourceYAML(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetRole(arg1:string,arg2:string,arg3:string):Promise<kube.RoleDetail>;

export function GetRoleBinding(arg1:string,arg2:string,arg3:string):Promise<kube.RoleBindingDetail>;

export function GetRuntimeClass(arg1:string,arg2:string):Promise<kube.RuntimeClassDetail>;

export function GetSecret(arg1:string,arg2:string,arg3:string):Promise<kube.SecretDetail>;

export function GetService(arg1:string,arg2:string,arg3:string):Promise<kube.ServiceDetail>;

export function GetServiceAccount(arg1:string,arg2:string,arg3:string):Promise<kube.ServiceAccountDetail>;

export function GetStatefulSet(arg1:string,arg2:string,arg3:string):Promise<kube.StatefulSetDetail>;

export function GetStorageClass(arg1:string,arg2:string):Promise<kube.StorageClassDetail>;

export function GetSubjectAccess(arg1:string,arg2:string,arg3:string,arg4:string):Promise<kube.SubjectAccess>;

export function GetValidatingWebhookConfiguration(arg1:string,arg2:string):Promise<kube.WebhookConfigurationDetail>;

export function GetVolumeAttachment(arg1:string,arg2:string):Promise<kube.VolumeAttachmentDetail>;

export function GetWorkloadRevisionTemplate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function HelmChartVersions(arg1:string,arg2:string):Promise<Array<string>>;

export function InstallHelmRelease(arg1:kube.HelmInstallOptions):Promise<kube.HelmDryRunResult>;

export function IsMetricsServerKlustrManaged(arg1:string):Promise<boolean>;

export function ListAPIServices(arg1:string):Promise<Array<kube.APIServiceInfo>>;

export function ListAccessSubjects(arg1:string):Promise<Array<kube.AccessSubject>>;

export function ListAccessibleKinds(arg1:string):Promise<Array<string>>;

export function ListArgoApplicationResources(arg1:string,arg2:string,arg3:string):Promise<Array<kube.ArgoApplicationResource>>;

export function ListArgoApplications(arg1:string,arg2:string):Promise<Array<kube.ArgoApplicationInfo>>;

export function ListCRDs(arg1:string):Promise<Array<kube.CRDInfo>>;

export function ListCSIDrivers(arg1:string):Promise<Array<kube.CSIDriverInfo>>;

export function ListCSINodes(arg1:string):Promise<Array<kube.CSINodeInfo>>;

export function ListCertificateSigningRequests(arg1:string):Promise<Array<kube.CertificateSigningRequestInfo>>;

export function ListClusterRoleBindings(arg1:string):Promise<Array<kube.ClusterRoleBindingInfo>>;

export function ListClusterRoles(arg1:string):Promise<Array<kube.ClusterRoleInfo>>;

export function ListClusterWarningEvents(arg1:string,arg2:number):Promise<Array<kube.EventInfo>>;

export function ListConfigMaps(arg1:string,arg2:string):Promise<Array<kube.ConfigMapInfo>>;

export function ListContexts():Promise<kube.Kubeconfig>;

export function ListCronJobs(arg1:string,arg2:string):Promise<Array<kube.CronJobInfo>>;

export function ListCustomResources(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<kube.CustomResourceInfo>>;

export function ListDaemonSetRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<kube.WorkloadRevision>>;

export function ListDaemonSets(arg1:string,arg2:string):Promise<Array<kube.DaemonSetInfo>>;

export function ListDeploymentRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<kube.WorkloadRevision>>;

export function ListDeployments(arg1:string,arg2:string):Promise<Array<kube.DeploymentInfo>>;

export function ListEndpointSlices(arg1:string,arg2:string):Promise<Array<kube.EndpointSliceInfo>>;

export function ListEndpoints(arg1:string,arg2:string):Promise<Array<kube.EndpointsInfo>>;

export function ListEvents(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<kube.EventInfo>>;

export function ListGRPCRoutes(arg1:string,arg2:string):Promise<Array<kube.GRPCRouteInfo>>;

export function ListGatewayClasses(arg1:string):Promise<Array<kube.GatewayClassInfo>>;

export function ListGateways(arg1:string,arg2:string):Promise<Array<kube.GatewayInfo>>;

export function ListHTTPRoutes(arg1:string,arg2:string):Promise<Array<kube.HTTPRouteInfo>>;

export function ListHelmReleaseHistory(arg1:string,arg2:string,arg3:string):Promise<Array<kube.HelmRevisionInfo>>;

export function ListHelmReleases(arg1:string,arg2:string):Promise<Array<kube.HelmReleaseInfo>>;

export function ListHelmRepos():Promise<Array<kube.HelmRepoInfo>>;

export function ListHorizontalPodAutoscalers(arg1:string,arg2:string):Promise<Array<kube.HorizontalPodAutoscalerInfo>>;

export function ListIngressClasses(arg1:string):Promise<Array<kube.IngressClassInfo>>;

export function ListIngresses(arg1:string,arg2:string):Promise<Array<kube.IngressInfo>>;

export function ListJobs(arg1:string,arg2:string):Promise<Array<kube.JobInfo>>;

export function ListLeases(arg1:string,arg2:string):Promise<Array<kube.LeaseInfo>>;

export function ListLimitRanges(arg1:string,arg2:string):Promise<Array<kube.LimitRangeInfo>>;

export function ListMutatingWebhookConfigurations(arg1:string):Promise<Array<kube.WebhookConfigurationInfo>>;

export function ListNamespaces(arg1:string):Promise<Array<kube.NamespaceInfo>>;

export function ListNetworkPolicies(arg1:string,arg2:string):Promise<Array<kube.NetworkPolicyInfo>>;

export function ListNodes(arg1:string):Promise<Array<kube.NodeInfo>>;

export function ListPersistentVolumeClaims(arg1:string,arg2:string):Promise<Array<kube.PersistentVolumeClaimInfo>>;

export function ListPersistentVolumes(arg1:string):Promise<Array<kube.PersistentVolumeInfo>>;

export function ListPodDisruptionBudgets(arg1:string,arg2:string):Promise<Array<kube.PodDisruptionBudgetInfo>>;

export function ListPodMetrics(arg1:string,arg2:string):Promise<Array<kube.PodMetrics>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<kube.PodInfo>>;

export function ListPortForwards():Promise<Array<kube.PortForwardInfo>>;

export function ListPriorityClasses(arg1:string):Promise<Array<kube.PriorityClassInfo>>;

export function ListReferenceGrants(arg1:string,arg2:string):Promise<Array<kube.ReferenceGrantInfo>>;

export function ListReplicaSets(arg1:string,arg2:string):Promise<Array<kube.ReplicaSetInfo>>;

export function ListReplicationControllers(arg1:string,arg2:string):Promise<Array<kube.ReplicationControllerInfo>>;

export function ListResourceQuotas(arg1:string,arg2:string):Promise<Array<kube.ResourceQuotaInfo>>;

export function ListRoleBindings(arg1:string,arg2:string):Promise<Array<kube.RoleBindingInfo>>;

export function ListRoles(arg1:string,arg2:string):Promise<Array<kube.RoleInfo>>;

export function ListRuntimeClasses(arg1:string):Promise<Array<kube.RuntimeClassInfo>>;

export function ListSecrets(arg1:string,arg2:string):Promise<Array<kube.SecretInfo>>;

export function ListServiceAccounts(arg1:string,arg2:string):Promise<Array<kube.ServiceAccountInfo>>;

export function ListServices(arg1:string,arg2:string):Promise<Array<kube.ServiceInfo>>;

export function ListStatefulSetRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<kube.WorkloadRevision>>;

export function ListStatefulSets(arg1:string,arg2:string):Promise<Array<kube.StatefulSetInfo>>;

export function ListStorageClasses(arg1:string):Promise<Array<kube.StorageClassInfo>>;

export function ListValidatingWebhookConfigurations(arg1:string):Promise<Array<kube.WebhookConfigurationInfo>>;

export function ListVolumeAttachments(arg1:string):Promise<Array<kube.VolumeAttachmentInfo>>;

export function PatchDeploymentPaused(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function PatchHPAReplicas(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function PingContext(arg1:string):Promise<kube.ServerVersion>;

export function PodLogTargets(arg1:string,arg2:string,arg3:Record<string, string>):Promise<Array<kube.PodLogTarget>>;

export function PodsForOwner(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<kube.PodInfo>>;

export function RecommendInsecureKubeletTLS(arg1:string):Promise<boolean>;

export function RefreshArgoApplication(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RemoveHelmRepo(arg1:string):Promise<void>;

export function ResizeExec(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartWorkload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RevealSecretValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RollbackDaemonSet(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function RollbackDeployment(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function RollbackHelmRelease(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function RollbackStatefulSet(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function ScaleResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function SearchHelmCharts(arg1:string):Promise<Array<kube.HelmChartSearchResult>>;

export function SendExecInput(arg1:string,arg2:string):Promise<void>;

export function StartExec(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<string>;

export function StartPodLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:number):Promise<string>;

export function StartPortForward(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<kube.PortForwardInfo>;

export function StartWatch(arg1:string):Promise<void>;

export function StopExec(arg1:string):Promise<void>;

export function StopPodLogs(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function StopWatch(arg1:string):Promise<void>;

export function SyncArgoApplication(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function UninstallHelmRelease(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UpdateHelmRepos():Promise<void>;

export function UpgradeHelmRelease(arg1:kube.HelmInstallOptions):Promise<kube.HelmDryRunResult>;

export function Version():Promise<string>;
