// Generated by npm run generate:api. Do not edit.
import * as bindings from '@/lib/wails/wailsjs/go/app/App'
import { app, kube, update } from '@/lib/wails/wailsjs/go/models'

export type AppDebugSession = app.DebugSession
export type ConditionDetail = kube.ConditionDetail
export type APIServiceDetail = kube.APIServiceDetail
export type APIServiceInfo = kube.APIServiceInfo
export type AccessSubject = kube.AccessSubject
export type AdmissionPolicyAuditAnnotation = kube.AdmissionPolicyAuditAnnotation
export type AdmissionPolicyMatchCondition = kube.AdmissionPolicyMatchCondition
export type AdmissionPolicyBindingDetail = kube.AdmissionPolicyBindingDetail
export type AdmissionPolicyBindingInfo = kube.AdmissionPolicyBindingInfo
export type AdmissionPolicyVariable = kube.AdmissionPolicyVariable
export type AdmissionPolicyMutation = kube.AdmissionPolicyMutation
export type AdmissionPolicyValidation = kube.AdmissionPolicyValidation
export type AdmissionPolicyDetail = kube.AdmissionPolicyDetail
export type AdmissionPolicyInfo = kube.AdmissionPolicyInfo
export type AllocatedDeviceDetail = kube.AllocatedDeviceDetail
export type ArgoAppProjectDestination = kube.ArgoAppProjectDestination
export type ArgoAppProjectSyncWindow = kube.ArgoAppProjectSyncWindow
export type ArgoAppProjectRole = kube.ArgoAppProjectRole
export type ArgoAppProjectGroupKind = kube.ArgoAppProjectGroupKind
export type ArgoAppProjectDetail = kube.ArgoAppProjectDetail
export type ArgoAppProjectInfo = kube.ArgoAppProjectInfo
export type ArgoApplicationCondition = kube.ArgoApplicationCondition
export type ArgoApplicationHealth = kube.ArgoApplicationHealth
export type ArgoApplicationHistoryEntry = kube.ArgoApplicationHistoryEntry
export type ArgoApplicationInfo = kube.ArgoApplicationInfo
export type ArgoApplicationResource = kube.ArgoApplicationResource
export type ArgoApplicationSetGeneratedApp = kube.ArgoApplicationSetGeneratedApp
export type ArgoApplicationSetGenerator = kube.ArgoApplicationSetGenerator
export type ArgoApplicationSetDetail = kube.ArgoApplicationSetDetail
export type ArgoApplicationSetInfo = kube.ArgoApplicationSetInfo
export type ArgoSyncResultResource = kube.ArgoSyncResultResource
export type ArgoOperationState = kube.ArgoOperationState
export type ArgoSyncResourceSelector = kube.ArgoSyncResourceSelector
export type ArgoSyncOptions = kube.ArgoSyncOptions
export type BackendRefDetail = kube.BackendRefDetail
export type PrinterColumn = kube.PrinterColumn
export type CRDInfo = kube.CRDInfo
export type CSIDriverDetail = kube.CSIDriverDetail
export type CSIDriverInfo = kube.CSIDriverInfo
export type CSINodeDriverDetail = kube.CSINodeDriverDetail
export type CSINodeDetail = kube.CSINodeDetail
export type CSINodeInfo = kube.CSINodeInfo
export type CertManagerCondition = kube.CertManagerCondition
export type CertManagerCertificateDetail = kube.CertManagerCertificateDetail
export type CertManagerCertificateInfo = kube.CertManagerCertificateInfo
export type CertManagerCertificateRequestDetail = kube.CertManagerCertificateRequestDetail
export type CertManagerCertificateRequestInfo = kube.CertManagerCertificateRequestInfo
export type CertManagerChallengeDetail = kube.CertManagerChallengeDetail
export type CertManagerChallengeInfo = kube.CertManagerChallengeInfo
export type CertManagerIssuerDetail = kube.CertManagerIssuerDetail
export type CertManagerIssuerInfo = kube.CertManagerIssuerInfo
export type CertManagerOrderDetail = kube.CertManagerOrderDetail
export type CertManagerOrderInfo = kube.CertManagerOrderInfo
export type CertificateSigningRequestDetail = kube.CertificateSigningRequestDetail
export type CertificateSigningRequestInfo = kube.CertificateSigningRequestInfo
export type ClusterPods = kube.ClusterPods
export type ClusterResource = kube.ClusterResource
export type ClusterOverview = kube.ClusterOverview
export type SubjectDetail = kube.SubjectDetail
export type RoleRefDetail = kube.RoleRefDetail
export type ClusterRoleBindingDetail = kube.ClusterRoleBindingDetail
export type ClusterRoleBindingInfo = kube.ClusterRoleBindingInfo
export type PolicyRuleDetail = kube.PolicyRuleDetail
export type ClusterRoleDetail = kube.ClusterRoleDetail
export type ClusterRoleInfo = kube.ClusterRoleInfo
export type ConfigMapDetail = kube.ConfigMapDetail
export type ConfigMapInfo = kube.ConfigMapInfo
export type ContainerResources = kube.ContainerResources
export type ContainerEnvFrom = kube.ContainerEnvFrom
export type EnvVarRef = kube.EnvVarRef
export type ContainerEnvVar = kube.ContainerEnvVar
export type ContainerPort = kube.ContainerPort
export type ContainerDetail = kube.ContainerDetail
export type ContainerSummary = kube.ContainerSummary
export type ContextInfo = kube.ContextInfo
export type CredentialProviderInfo = kube.CredentialProviderInfo
export type CredentialStatus = kube.CredentialStatus
export type CronJobDetail = kube.CronJobDetail
export type CronJobInfo = kube.CronJobInfo
export type CustomResourceInfo = kube.CustomResourceInfo
export type DaemonSetDetail = kube.DaemonSetDetail
export type DaemonSetInfo = kube.DaemonSetInfo
export type DeploymentDetail = kube.DeploymentDetail
export type DeploymentInfo = kube.DeploymentInfo
export type DeviceSelectorDetail = kube.DeviceSelectorDetail
export type DeviceClassDetail = kube.DeviceClassDetail
export type DeviceClassInfo = kube.DeviceClassInfo
export type DeviceRequestDetail = kube.DeviceRequestDetail
export type EndpointSlicePort = kube.EndpointSlicePort
export type EndpointSliceEndpoint = kube.EndpointSliceEndpoint
export type EndpointSliceDetail = kube.EndpointSliceDetail
export type EndpointSliceInfo = kube.EndpointSliceInfo
export type EndpointsSubsetPort = kube.EndpointsSubsetPort
export type EndpointsSubsetAddress = kube.EndpointsSubsetAddress
export type EndpointsSubset = kube.EndpointsSubset
export type EndpointsDetail = kube.EndpointsDetail
export type EndpointsInfo = kube.EndpointsInfo
export type EventInfo = kube.EventInfo
export type FlowSchemaRuleDetail = kube.FlowSchemaRuleDetail
export type FlowSchemaDetail = kube.FlowSchemaDetail
export type FlowSchemaInfo = kube.FlowSchemaInfo
export type FluxAlertSource = kube.FluxAlertSource
export type FluxCondition = kube.FluxCondition
export type FluxAlertDetail = kube.FluxAlertDetail
export type FluxAlertInfo = kube.FluxAlertInfo
export type FluxBucketDetail = kube.FluxBucketDetail
export type FluxBucketInfo = kube.FluxBucketInfo
export type FluxGitRepositoryDetail = kube.FluxGitRepositoryDetail
export type FluxGitRepositoryInfo = kube.FluxGitRepositoryInfo
export type FluxHelmReleaseDetail = kube.FluxHelmReleaseDetail
export type FluxHelmReleaseInfo = kube.FluxHelmReleaseInfo
export type FluxHelmRepositoryDetail = kube.FluxHelmRepositoryDetail
export type FluxHelmRepositoryInfo = kube.FluxHelmRepositoryInfo
export type FluxKustomizationDetail = kube.FluxKustomizationDetail
export type FluxKustomizationInfo = kube.FluxKustomizationInfo
export type FluxOCIRepositoryDetail = kube.FluxOCIRepositoryDetail
export type FluxOCIRepositoryInfo = kube.FluxOCIRepositoryInfo
export type FluxProviderDetail = kube.FluxProviderDetail
export type FluxProviderInfo = kube.FluxProviderInfo
export type FluxReceiverDetail = kube.FluxReceiverDetail
export type FluxReceiverInfo = kube.FluxReceiverInfo
export type RouteParentStatusDetail = kube.RouteParentStatusDetail
export type GRPCRouteMatchDetail = kube.GRPCRouteMatchDetail
export type GRPCRouteRuleDetail = kube.GRPCRouteRuleDetail
export type ParentRefDetail = kube.ParentRefDetail
export type GRPCRouteDetail = kube.GRPCRouteDetail
export type GRPCRouteInfo = kube.GRPCRouteInfo
export type GatewayClassDetail = kube.GatewayClassDetail
export type GatewayClassInfo = kube.GatewayClassInfo
export type ListenerDetail = kube.ListenerDetail
export type GatewayDetail = kube.GatewayDetail
export type GatewayInfo = kube.GatewayInfo
export type HPAMetricTarget = kube.HPAMetricTarget
export type HTTPRouteMatchDetail = kube.HTTPRouteMatchDetail
export type HTTPRouteRuleDetail = kube.HTTPRouteRuleDetail
export type HTTPRouteDetail = kube.HTTPRouteDetail
export type HTTPRouteInfo = kube.HTTPRouteInfo
export type HelmChartSearchResult = kube.HelmChartSearchResult
export type HelmDryRunResult = kube.HelmDryRunResult
export type HelmInstallOptions = kube.HelmInstallOptions
export type HelmRevisionInfo = kube.HelmRevisionInfo
export type HelmReleaseInfo = kube.HelmReleaseInfo
export type HelmReleaseDetail = kube.HelmReleaseDetail
export type HelmRepoInfo = kube.HelmRepoInfo
export type HorizontalPodAutoscalerDetail = kube.HorizontalPodAutoscalerDetail
export type HorizontalPodAutoscalerInfo = kube.HorizontalPodAutoscalerInfo
export type IPAddressDetail = kube.IPAddressDetail
export type IPAddressInfo = kube.IPAddressInfo
export type IngressClassDetail = kube.IngressClassDetail
export type IngressClassInfo = kube.IngressClassInfo
export type IngressTLSDetail = kube.IngressTLSDetail
export type IngressPathDetail = kube.IngressPathDetail
export type IngressRuleDetail = kube.IngressRuleDetail
export type IngressDetail = kube.IngressDetail
export type IngressInfo = kube.IngressInfo
export type IstioSubset = kube.IstioSubset
export type IstioDestinationRuleDetail = kube.IstioDestinationRuleDetail
export type IstioDestinationRuleInfo = kube.IstioDestinationRuleInfo
export type IstioDestinationWeight = kube.IstioDestinationWeight
export type IstioPortMTLS = kube.IstioPortMTLS
export type IstioPeerAuthenticationDetail = kube.IstioPeerAuthenticationDetail
export type IstioPeerAuthenticationInfo = kube.IstioPeerAuthenticationInfo
export type IstioRouteRule = kube.IstioRouteRule
export type IstioVirtualServiceDetail = kube.IstioVirtualServiceDetail
export type IstioVirtualServiceInfo = kube.IstioVirtualServiceInfo
export type JobDetail = kube.JobDetail
export type JobInfo = kube.JobInfo
export type KarpenterNodeClaimInfo = kube.KarpenterNodeClaimInfo
export type KarpenterNodePoolInfo = kube.KarpenterNodePoolInfo
export type Kubeconfig = kube.Kubeconfig
export type LeaseDetail = kube.LeaseDetail
export type LeaseInfo = kube.LeaseInfo
export type LimitRangeItem = kube.LimitRangeItem
export type LimitRangeDetail = kube.LimitRangeDetail
export type LimitRangeInfo = kube.LimitRangeInfo
export type MutationDiff = kube.MutationDiff
export type NamespaceDetail = kube.NamespaceDetail
export type NamespaceInfo = kube.NamespaceInfo
export type NetworkPolicyDetail = kube.NetworkPolicyDetail
export type NetworkPolicyInfo = kube.NetworkPolicyInfo
export type NodeTaintDetail = kube.NodeTaintDetail
export type NodeDetail = kube.NodeDetail
export type NodeInfo = kube.NodeInfo
export type NodeMetrics = kube.NodeMetrics
export type ObjectRefDetail = kube.ObjectRefDetail
export type OwnerRef = kube.OwnerRef
export type PersistentVolumeClaimDetail = kube.PersistentVolumeClaimDetail
export type PersistentVolumeClaimInfo = kube.PersistentVolumeClaimInfo
export type PersistentVolumeDetail = kube.PersistentVolumeDetail
export type PersistentVolumeInfo = kube.PersistentVolumeInfo
export type PodContainerBrief = kube.PodContainerBrief
export type PodDetail = kube.PodDetail
export type PodDisruptionBudgetDetail = kube.PodDisruptionBudgetDetail
export type PodDisruptionBudgetInfo = kube.PodDisruptionBudgetInfo
export type PodInfo = kube.PodInfo
export type PodLogTarget = kube.PodLogTarget
export type PodMetrics = kube.PodMetrics
export type PortForwardInfo = kube.PortForwardInfo
export type PriorityClassDetail = kube.PriorityClassDetail
export type PriorityClassInfo = kube.PriorityClassInfo
export type PriorityLevelConfigurationDetail = kube.PriorityLevelConfigurationDetail
export type PriorityLevelConfigurationInfo = kube.PriorityLevelConfigurationInfo
export type ReferenceGrantToDetail = kube.ReferenceGrantToDetail
export type ReferenceGrantFromDetail = kube.ReferenceGrantFromDetail
export type ReferenceGrantDetail = kube.ReferenceGrantDetail
export type ReferenceGrantInfo = kube.ReferenceGrantInfo
export type ReplicaSetDetail = kube.ReplicaSetDetail
export type ReplicaSetInfo = kube.ReplicaSetInfo
export type ReplicationControllerDetail = kube.ReplicationControllerDetail
export type ReplicationControllerInfo = kube.ReplicationControllerInfo
export type ResourceClaimDetail = kube.ResourceClaimDetail
export type ResourceClaimInfo = kube.ResourceClaimInfo
export type ResourceClaimTemplateDetail = kube.ResourceClaimTemplateDetail
export type ResourceClaimTemplateInfo = kube.ResourceClaimTemplateInfo
export type ResourceQuotaEntry = kube.ResourceQuotaEntry
export type ResourceQuotaDetail = kube.ResourceQuotaDetail
export type ResourceQuotaInfo = kube.ResourceQuotaInfo
export type ResourceSliceDeviceDetail = kube.ResourceSliceDeviceDetail
export type ResourceSliceDetail = kube.ResourceSliceDetail
export type ResourceSliceInfo = kube.ResourceSliceInfo
export type RoleBindingDetail = kube.RoleBindingDetail
export type RoleBindingInfo = kube.RoleBindingInfo
export type RoleDetail = kube.RoleDetail
export type RoleInfo = kube.RoleInfo
export type RuntimeClassDetail = kube.RuntimeClassDetail
export type RuntimeClassInfo = kube.RuntimeClassInfo
export type SecretKeyInfo = kube.SecretKeyInfo
export type SecretDetail = kube.SecretDetail
export type SecretInfo = kube.SecretInfo
export type SecretValueResult = kube.SecretValueResult
export type ServerVersion = kube.ServerVersion
export type ServiceAccountDetail = kube.ServiceAccountDetail
export type ServiceAccountInfo = kube.ServiceAccountInfo
export type ServiceCIDRDetail = kube.ServiceCIDRDetail
export type ServiceCIDRInfo = kube.ServiceCIDRInfo
export type ServicePortDetail = kube.ServicePortDetail
export type ServiceDetail = kube.ServiceDetail
export type ServiceInfo = kube.ServiceInfo
export type StatefulSetDetail = kube.StatefulSetDetail
export type StatefulSetInfo = kube.StatefulSetInfo
export type StorageClassDetail = kube.StorageClassDetail
export type StorageClassInfo = kube.StorageClassInfo
export type SubjectAccessRule = kube.SubjectAccessRule
export type SubjectAccess = kube.SubjectAccess
export type SystemTerminal = kube.SystemTerminal
export type VolumeAttachmentDetail = kube.VolumeAttachmentDetail
export type VolumeAttachmentInfo = kube.VolumeAttachmentInfo
export type WebhookSummary = kube.WebhookSummary
export type WebhookConfigurationDetail = kube.WebhookConfigurationDetail
export type WebhookConfigurationInfo = kube.WebhookConfigurationInfo
export type WorkloadRevision = kube.WorkloadRevision
export type UpdateResult = update.Result

export const generatedApi = {
  addHelmRepo: bindings.AddHelmRepo,
  applyResourceYAML: bindings.ApplyResourceYAML,
  approveCertificateSigningRequest: bindings.ApproveCertificateSigningRequest,
  captureCredentials: bindings.CaptureCredentials,
  certManagerCertificateRequestsFor: bindings.CertManagerCertificateRequestsFor,
  certManagerChallengesFor: bindings.CertManagerChallengesFor,
  certManagerOrdersFor: bindings.CertManagerOrdersFor,
  checkForUpdate: bindings.CheckForUpdate,
  clearCredentialMapping: bindings.ClearCredentialMapping,
  cordonNode: bindings.CordonNode,
  deleteArgoApplication: bindings.DeleteArgoApplication,
  deleteResource: bindings.DeleteResource,
  denyCertificateSigningRequest: bindings.DenyCertificateSigningRequest,
  drainNode: bindings.DrainNode,
  dryRunApplyResourceYAML: bindings.DryRunApplyResourceYAML,
  ensureCustomResourceWatch: bindings.EnsureCustomResourceWatch,
  fetchMetricsServerManifest: bindings.FetchMetricsServerManifest,
  getAPIService: bindings.GetAPIService,
  getArgoAppProject: bindings.GetArgoAppProject,
  getArgoApplicationHealth: bindings.GetArgoApplicationHealth,
  getArgoApplicationOperationState: bindings.GetArgoApplicationOperationState,
  getArgoApplicationSet: bindings.GetArgoApplicationSet,
  getCSIDriver: bindings.GetCSIDriver,
  getCSINode: bindings.GetCSINode,
  getCertManagerCertificate: bindings.GetCertManagerCertificate,
  getCertManagerCertificateRequest: bindings.GetCertManagerCertificateRequest,
  getCertManagerChallenge: bindings.GetCertManagerChallenge,
  getCertManagerClusterIssuer: bindings.GetCertManagerClusterIssuer,
  getCertManagerIssuer: bindings.GetCertManagerIssuer,
  getCertManagerOrder: bindings.GetCertManagerOrder,
  getCertificateSigningRequest: bindings.GetCertificateSigningRequest,
  getClusterOverview: bindings.GetClusterOverview,
  getClusterRole: bindings.GetClusterRole,
  getClusterRoleBinding: bindings.GetClusterRoleBinding,
  getConfigMap: bindings.GetConfigMap,
  getCronJob: bindings.GetCronJob,
  getCustomResourceYAML: bindings.GetCustomResourceYAML,
  getDaemonSet: bindings.GetDaemonSet,
  getDeployment: bindings.GetDeployment,
  getDeviceClass: bindings.GetDeviceClass,
  getEndpointSlice: bindings.GetEndpointSlice,
  getEndpoints: bindings.GetEndpoints,
  getFlowSchema: bindings.GetFlowSchema,
  getFluxAlert: bindings.GetFluxAlert,
  getFluxBucket: bindings.GetFluxBucket,
  getFluxGitRepository: bindings.GetFluxGitRepository,
  getFluxHelmRelease: bindings.GetFluxHelmRelease,
  getFluxHelmRepository: bindings.GetFluxHelmRepository,
  getFluxKustomization: bindings.GetFluxKustomization,
  getFluxOCIRepository: bindings.GetFluxOCIRepository,
  getFluxProvider: bindings.GetFluxProvider,
  getFluxReceiver: bindings.GetFluxReceiver,
  getGRPCRoute: bindings.GetGRPCRoute,
  getGateway: bindings.GetGateway,
  getGatewayClass: bindings.GetGatewayClass,
  getHTTPRoute: bindings.GetHTTPRoute,
  getHelmRelease: bindings.GetHelmRelease,
  getHorizontalPodAutoscaler: bindings.GetHorizontalPodAutoscaler,
  getIPAddress: bindings.GetIPAddress,
  getIngress: bindings.GetIngress,
  getIngressClass: bindings.GetIngressClass,
  getIstioDestinationRule: bindings.GetIstioDestinationRule,
  getIstioPeerAuthentication: bindings.GetIstioPeerAuthentication,
  getIstioVirtualService: bindings.GetIstioVirtualService,
  getJob: bindings.GetJob,
  getLease: bindings.GetLease,
  getLimitRange: bindings.GetLimitRange,
  getMutatingAdmissionPolicy: bindings.GetMutatingAdmissionPolicy,
  getMutatingAdmissionPolicyBinding: bindings.GetMutatingAdmissionPolicyBinding,
  getMutatingWebhookConfiguration: bindings.GetMutatingWebhookConfiguration,
  getNamespace: bindings.GetNamespace,
  getNetworkPolicy: bindings.GetNetworkPolicy,
  getNode: bindings.GetNode,
  getPersistentVolume: bindings.GetPersistentVolume,
  getPersistentVolumeClaim: bindings.GetPersistentVolumeClaim,
  getPod: bindings.GetPod,
  getPodDisruptionBudget: bindings.GetPodDisruptionBudget,
  getPriorityClass: bindings.GetPriorityClass,
  getPriorityLevelConfiguration: bindings.GetPriorityLevelConfiguration,
  getReferenceGrant: bindings.GetReferenceGrant,
  getReplicaSet: bindings.GetReplicaSet,
  getReplicationController: bindings.GetReplicationController,
  getResourceClaim: bindings.GetResourceClaim,
  getResourceClaimTemplate: bindings.GetResourceClaimTemplate,
  getResourceQuota: bindings.GetResourceQuota,
  getResourceSlice: bindings.GetResourceSlice,
  getResourceYAML: bindings.GetResourceYAML,
  getRole: bindings.GetRole,
  getRoleBinding: bindings.GetRoleBinding,
  getRuntimeClass: bindings.GetRuntimeClass,
  getSecret: bindings.GetSecret,
  getService: bindings.GetService,
  getServiceAccount: bindings.GetServiceAccount,
  getServiceCIDR: bindings.GetServiceCIDR,
  getStatefulSet: bindings.GetStatefulSet,
  getStorageClass: bindings.GetStorageClass,
  getSubjectAccess: bindings.GetSubjectAccess,
  getValidatingAdmissionPolicy: bindings.GetValidatingAdmissionPolicy,
  getValidatingAdmissionPolicyBinding: bindings.GetValidatingAdmissionPolicyBinding,
  getValidatingWebhookConfiguration: bindings.GetValidatingWebhookConfiguration,
  getVolumeAttachment: bindings.GetVolumeAttachment,
  getWorkloadRevisionTemplate: bindings.GetWorkloadRevisionTemplate,
  helmChartVersions: bindings.HelmChartVersions,
  installHelmRelease: bindings.InstallHelmRelease,
  isMetricsServerKlustrManaged: bindings.IsMetricsServerKlustrManaged,
  listAPIServices: bindings.ListAPIServices,
  listAccessSubjects: bindings.ListAccessSubjects,
  listAccessibleKinds: bindings.ListAccessibleKinds,
  listArgoAppProjects: bindings.ListArgoAppProjects,
  listArgoApplicationHistory: bindings.ListArgoApplicationHistory,
  listArgoApplicationResources: bindings.ListArgoApplicationResources,
  listArgoApplicationSets: bindings.ListArgoApplicationSets,
  listArgoApplications: bindings.ListArgoApplications,
  listCRDs: bindings.ListCRDs,
  listCSIDrivers: bindings.ListCSIDrivers,
  listCSINodes: bindings.ListCSINodes,
  listCertManagerCertificateRequests: bindings.ListCertManagerCertificateRequests,
  listCertManagerCertificates: bindings.ListCertManagerCertificates,
  listCertManagerChallenges: bindings.ListCertManagerChallenges,
  listCertManagerClusterIssuers: bindings.ListCertManagerClusterIssuers,
  listCertManagerIssuers: bindings.ListCertManagerIssuers,
  listCertManagerOrders: bindings.ListCertManagerOrders,
  listCertificateSigningRequests: bindings.ListCertificateSigningRequests,
  listClusterRoleBindings: bindings.ListClusterRoleBindings,
  listClusterRoles: bindings.ListClusterRoles,
  listClusterWarningEvents: bindings.ListClusterWarningEvents,
  listConfigMaps: bindings.ListConfigMaps,
  listContexts: bindings.ListContexts,
  listCredentialProfiles: bindings.ListCredentialProfiles,
  listCredentialProviders: bindings.ListCredentialProviders,
  listCredentialStatuses: bindings.ListCredentialStatuses,
  listCronJobs: bindings.ListCronJobs,
  listCustomResources: bindings.ListCustomResources,
  listDaemonSetRevisions: bindings.ListDaemonSetRevisions,
  listDaemonSets: bindings.ListDaemonSets,
  listDeploymentRevisions: bindings.ListDeploymentRevisions,
  listDeployments: bindings.ListDeployments,
  listDeviceClasses: bindings.ListDeviceClasses,
  listEndpointSlices: bindings.ListEndpointSlices,
  listEndpoints: bindings.ListEndpoints,
  listEvents: bindings.ListEvents,
  listFlowSchemas: bindings.ListFlowSchemas,
  listFluxAlerts: bindings.ListFluxAlerts,
  listFluxBuckets: bindings.ListFluxBuckets,
  listFluxGitRepositories: bindings.ListFluxGitRepositories,
  listFluxHelmReleases: bindings.ListFluxHelmReleases,
  listFluxHelmRepositories: bindings.ListFluxHelmRepositories,
  listFluxKustomizations: bindings.ListFluxKustomizations,
  listFluxOCIRepositories: bindings.ListFluxOCIRepositories,
  listFluxProviders: bindings.ListFluxProviders,
  listFluxReceivers: bindings.ListFluxReceivers,
  listGRPCRoutes: bindings.ListGRPCRoutes,
  listGatewayClasses: bindings.ListGatewayClasses,
  listGateways: bindings.ListGateways,
  listHTTPRoutes: bindings.ListHTTPRoutes,
  listHelmReleaseHistory: bindings.ListHelmReleaseHistory,
  listHelmReleases: bindings.ListHelmReleases,
  listHelmRepos: bindings.ListHelmRepos,
  listHorizontalPodAutoscalers: bindings.ListHorizontalPodAutoscalers,
  listIPAddresses: bindings.ListIPAddresses,
  listIngressClasses: bindings.ListIngressClasses,
  listIngresses: bindings.ListIngresses,
  listIstioDestinationRules: bindings.ListIstioDestinationRules,
  listIstioPeerAuthentications: bindings.ListIstioPeerAuthentications,
  listIstioVirtualServices: bindings.ListIstioVirtualServices,
  listJobs: bindings.ListJobs,
  listKarpenterNodeClaims: bindings.ListKarpenterNodeClaims,
  listKarpenterNodePools: bindings.ListKarpenterNodePools,
  listLeases: bindings.ListLeases,
  listLimitRanges: bindings.ListLimitRanges,
  listMutatingAdmissionPolicies: bindings.ListMutatingAdmissionPolicies,
  listMutatingAdmissionPolicyBindings: bindings.ListMutatingAdmissionPolicyBindings,
  listMutatingWebhookConfigurations: bindings.ListMutatingWebhookConfigurations,
  listNamespaces: bindings.ListNamespaces,
  listNetworkPolicies: bindings.ListNetworkPolicies,
  listNodeClaimNode: bindings.ListNodeClaimNode,
  listNodeMetrics: bindings.ListNodeMetrics,
  listNodePoolNodes: bindings.ListNodePoolNodes,
  listNodes: bindings.ListNodes,
  listPersistentVolumeClaims: bindings.ListPersistentVolumeClaims,
  listPersistentVolumes: bindings.ListPersistentVolumes,
  listPodDisruptionBudgets: bindings.ListPodDisruptionBudgets,
  listPodMetrics: bindings.ListPodMetrics,
  listPods: bindings.ListPods,
  listPortForwards: bindings.ListPortForwards,
  listPriorityClasses: bindings.ListPriorityClasses,
  listPriorityLevelConfigurations: bindings.ListPriorityLevelConfigurations,
  listReferenceGrants: bindings.ListReferenceGrants,
  listReplicaSets: bindings.ListReplicaSets,
  listReplicationControllers: bindings.ListReplicationControllers,
  listResourceClaimTemplates: bindings.ListResourceClaimTemplates,
  listResourceClaims: bindings.ListResourceClaims,
  listResourceQuotas: bindings.ListResourceQuotas,
  listResourceSlices: bindings.ListResourceSlices,
  listRoleBindings: bindings.ListRoleBindings,
  listRoles: bindings.ListRoles,
  listRuntimeClasses: bindings.ListRuntimeClasses,
  listSecrets: bindings.ListSecrets,
  listServiceAccounts: bindings.ListServiceAccounts,
  listServiceCIDRs: bindings.ListServiceCIDRs,
  listServices: bindings.ListServices,
  listStatefulSetRevisions: bindings.ListStatefulSetRevisions,
  listStatefulSets: bindings.ListStatefulSets,
  listStorageClasses: bindings.ListStorageClasses,
  listSystemTerminals: bindings.ListSystemTerminals,
  listValidatingAdmissionPolicies: bindings.ListValidatingAdmissionPolicies,
  listValidatingAdmissionPolicyBindings: bindings.ListValidatingAdmissionPolicyBindings,
  listValidatingWebhookConfigurations: bindings.ListValidatingWebhookConfigurations,
  listVolumeAttachments: bindings.ListVolumeAttachments,
  openInSystemTerminal: bindings.OpenInSystemTerminal,
  openLocalTerminal: bindings.OpenLocalTerminal,
  openPodExecInSystemTerminal: bindings.OpenPodExecInSystemTerminal,
  patchDeploymentPaused: bindings.PatchDeploymentPaused,
  patchHPAReplicas: bindings.PatchHPAReplicas,
  pingContext: bindings.PingContext,
  podLogTargets: bindings.PodLogTargets,
  podsForOwner: bindings.PodsForOwner,
  recommendInsecureKubeletTLS: bindings.RecommendInsecureKubeletTLS,
  reconcileFluxResource: bindings.ReconcileFluxResource,
  refreshArgoApplication: bindings.RefreshArgoApplication,
  removeHelmRepo: bindings.RemoveHelmRepo,
  renewCertificate: bindings.RenewCertificate,
  resizeExec: bindings.ResizeExec,
  resizeLocalTerminal: bindings.ResizeLocalTerminal,
  resizePodResources: bindings.ResizePodResources,
  restartWorkload: bindings.RestartWorkload,
  revealSecretValue: bindings.RevealSecretValue,
  rollbackArgoApplication: bindings.RollbackArgoApplication,
  rollbackDaemonSet: bindings.RollbackDaemonSet,
  rollbackDeployment: bindings.RollbackDeployment,
  rollbackHelmRelease: bindings.RollbackHelmRelease,
  rollbackStatefulSet: bindings.RollbackStatefulSet,
  saveTextFile: bindings.SaveTextFile,
  scaleResource: bindings.ScaleResource,
  searchHelmCharts: bindings.SearchHelmCharts,
  sendExecInput: bindings.SendExecInput,
  sendLocalTerminalInput: bindings.SendLocalTerminalInput,
  setArgoApplicationAutomation: bindings.SetArgoApplicationAutomation,
  setCredentialMapping: bindings.SetCredentialMapping,
  setFluxResourceSuspended: bindings.SetFluxResourceSuspended,
  setReadOnly: bindings.SetReadOnly,
  startExec: bindings.StartExec,
  startNodeShell: bindings.StartNodeShell,
  startPodDebug: bindings.StartPodDebug,
  startPodLogs: bindings.StartPodLogs,
  startPortForward: bindings.StartPortForward,
  startWatch: bindings.StartWatch,
  stopExec: bindings.StopExec,
  stopLocalTerminal: bindings.StopLocalTerminal,
  stopPodLogs: bindings.StopPodLogs,
  stopPortForward: bindings.StopPortForward,
  stopWatch: bindings.StopWatch,
  syncArgoApplication: bindings.SyncArgoApplication,
  uninstallHelmRelease: bindings.UninstallHelmRelease,
  updateHelmRepos: bindings.UpdateHelmRepos,
  upgradeHelmRelease: bindings.UpgradeHelmRelease,
  version: bindings.Version,
}
